### ISSUE TITLE
Truncated ad action menu

### ISSUE THREAD

**Issue by jhamrick** [NYUCCL/psiTurk#104]
I am not sure if this is the correct place to report issues on psiturk.org itself, but in the dashboard, if you click on the action menu for an ad which is at the bottom of the list, it gets truncated:

![image](https://cloud.githubusercontent.com/assets/83444/3209617/aeedb10e-ee7a-11e3-82a5-d8c62fbbf02b.png)

**Comment by deargle** [comment]
+1

**Comment by kupitzc** [comment]
Same thing is still happening, at least for me...

**Comment by deargle** [comment]
It's a bug in bootstrap v3.1.0: https://github.com/twbs/bootstrap/issues/12683

**Comment by deargle** [comment]
... fixed in v3.2.0, https://github.com/twbs/bootstrap/releases/tag/v3.2.0
