### ISSUE TITLE
HIT Duration < 1 hr?

### ISSUE THREAD

**Issue by JSlote** [NYUCCL/psiTurk#137]
It would be great to have a way to specify hit duration in hours:minutes rather than just hours. I'll get on this and hopefully submit a pull request today or tomorrow.

**Comment by adamliter** [comment]
Is there any possibility of getting this feature on the stable branch, or does the development branch really need to be installed in order to use it?

**Comment by adamliter** [comment]
By the way, could somebody explain to me what the difference between `cutoff_time` in `config.txt` and the duration that you set when you create a hit is? It seems to me like they are the same thing, but I'm guessing I might be misunderstanding something.

If they are the same thing, it seems odd that you can set the same thing in two different ways and that you can set them to be inconsistent.

So I assume they're not the same thing? What's the difference between them? Thanks! :smile:

**Comment by adamliter** [comment]
For anyone wondering the same thing that I was immediately above, this has been addressed in [the Google group thread called "cutoff vs HIT duration"](https://groups.google.com/forum/#!topic/psiturk/v24ndasQy5U):

> anything in the [Sever Parameters] refer to the gunicorn server.  So the cutoff_time there refers to (I believe) how long a socket will stay open waiting without data being passed.  it is not related to anything on AMT

**Comment by deargle** [comment]
@adamliter I'm still a github noob but I think this thread is invisible since it's closed unless username mentions are included. @gureckis the docs advertise that this feature works but it wasn't carried over into master code. If this is the right way to do it, I'm going to try a pull request that re-incorporates @JSlote 's commits into the current master branch.

**Comment by deargle** [comment]
I should have poked around a bit more and thought a bit more before commenting. #180 made it so that fractional hours work, using a decimal format. I'll just PR the docs to point that out.

Also see #165

**Comment by adamliter** [comment]
@deargle With the stable release of psiTurk on PyPI (2.1.2), the decimal format does not work:

```
https://psiturk.org
 ______   ______     __     ______   __  __     ______     __  __
/\  == \ /\  ___\   /\ \   /\__  _\ /\ \/\ \   /\  == \   /\ \/ /
\ \  _-/ \ \___  \  \ \ \  \/_/\ \/ \ \ \_\ \  \ \  __<   \ \  _"-.
 \ \_\    \/\_____\  \ \_\    \ \_\  \ \_____\  \ \_\ \_\  \ \_\ \_\
  \/_/     \/_____/   \/_/     \/_/   \/_____/   \/_/ /_/   \/_/\/_/

             an open platform for science on Amazon Mechanical Turk

--------------------------------------------------------------------
System status:

Hi all, You need to be running psiTurk version >= 2.0.0 to use the
Ad Server feature!

The latest stable version is 2.1.2.

Check https://github.com/NYUCCL/psiTurk or https://psiturk.org for
latest info.
psiTurk version 2.1.2
Type "help" for more information.
[psiTurk server:off mode:sdbx #HITs:0]$ server on
Experiment server launching...
Now serving on http://0.0.0.0:22362
[psiTurk server:on mode:sdbx #HITs:0]$ hit create
number of participants? 1
reward per HIT? 0.00
duration of hit (in hours)? 0.5
*** duration must be a whole number
[psiTurk server:on mode:sdbx #HITs:0]$ hit create
number of participants? 1
reward per HIT? 0.00
duration of hit (in hours)? 1.5
*** duration must be a whole number
[psiTurk server:on mode:sdbx #HITs:0]$
```

**Comment by deargle** [comment]
You can get the feature by installing from master: `pip install git+
https://github.com/NYUCCL/psiTurk.git`

**Comment by deargle** [comment]
Also, @gureckis said in another issue that it's by design that the docs for psiturk point to master instead of to the most recent release, so I'll keep the PR up.

**Comment by adamliter** [comment]
@deargle (and cc: @gureckis), that doesn't make much sense to me given that the recommended ways of installing in both the [docs](http://psiturk.readthedocs.org/en/latest/install.html#install-stable-version-via-pypi) and the [webpage](http://psiturk.org/quick_start/) say to do:

    pip install psiturk

The docs—but not the website—do go on to explain how to install from GitHub, but this is characterized as "install[ing] the bleeding-edge development version". To me, at least, this suggests that the docs will match the version installed with `pip` via PyPI.

If the docs are going to match the GitHub version but not the stable release version on PyPI, it seems like there should at least be a note about this in the documentation, and perhaps the recommended way on the psiTurk website of installing should be changed?

But, at any rate, thanks for the clarification, @deargle :smile:
