### ISSUE TITLE
hit creation example has invalid syntax

### ISSUE THREAD

**Issue by grbritz** [NYUCCL/psiTurk#165]
In the documentation on hit create, it shows setting time limit of 1:30, but when trying to create a new hit with that time, the error "*** durations must be a whole number" is shown.
![screen shot 2015-02-05 at 10 31 24 am](https://cloud.githubusercontent.com/assets/1458268/6066481/282fe24c-ad22-11e4-8303-5dbaefa97ef2.png)

**Comment by gureckis** [comment]
Sorry, we have a slight problem where the docs website pulls from the dev branch (so new docs release quickly) but most people might be using master.  In dev this syntax works, in master, durations must be a whole number (e.g., "1"() and you can't have fractions of hours.
