### ISSUE TITLE
create unified python API

### ISSUE THREAD

**Issue by alexanderrich** [NYUCCL/psiTurk#167]
In the long run, it would be great to have a unified python API for psiturk. Currently a non-negligible amount of important programming logic occurs in the psiturk_shell class, which is unfortunate (and largely my own fault!) because these functions can be tough to call from another python module. Moving as much logic as possible out of the shell methods and creating an API which could be used for everything from turning on/off the server to creating hits and bonusing workers would make it easy to implement things like incrementally adding to hits (Issue #101) and would also open the door for people to dream up crazy stuff with automated data collection/etc.

**Comment by gureckis** [comment]
yeah, abstracting this stuff somewhat would help move back to the GUI dashboard feature which we paused while we worked out basic functionality.
