### ISSUE TITLE
Problems with readline

### ISSUE THREAD

**Issue by john-guerra** [NYUCCL/psiTurk#173]
Hi I'm trying to run the example using psiturk but I'm getting this error:

```
$ psiturk
libedit version of readline detected.
readline will not be well behaved, which may cause all sorts
of problems for the psiTurk shell. We highly recommend installing
the gnu version of readline by running "sudo pip install gnureadline".
Note: "pip install readline" will NOT work because of how the OSX
pythonpath is structured.
Traceback (most recent call last):
  File "/usr/local/bin/psiturk", line 9, in <module>
    load_entry_point('PsiTurk==2.1.2', 'console_scripts', 'psiturk')()
  File "/Library/Python/2.7/site-packages/psiturk/command_line.py", line 14, in process
    launch_shell()
  File "/Library/Python/2.7/site-packages/psiturk/command_line.py", line 104, in launch_shell
    ps.run(cabinmode=args.cabinmode)
  File "/Library/Python/2.7/site-packages/psiturk/psiturk_shell.py", line 1787, in run
    shell.cmdloop()
  File "/Library/Python/2.7/site-packages/cmd2.py", line 1299, in cmdloop
    self._cmdloop()   
  File "/Library/Python/2.7/site-packages/cmd2.py", line 910, in _cmdloop
    self.preloop()
  File "/Library/Python/2.7/site-packages/psiturk/psiturk_shell.py", line 186, in preloop
    readline.read_history_file('.psiturk_history')
IOError: [Errno 22] Invalid argument
```

I have installed the gnureadline package, but it seems like for some reason psiturk is still getting the libedit version. Is this a bug?

**Comment by john-guerra** [comment]
Changing line 21 of 

```
/Library/Python/2.7/site-packages/psiturk/psiturk_shell.py
```

from

```
import gnureadline as readline
```

to

```
import gnureadline as readline
``` 

fixed the problem

**Comment by gureckis** [comment]
Sorry, what are the differences between these two lines?

**Comment by john-guerra** [comment]
Ups, my bad, I corrected my comment so people don't get confused

**Comment by brendantcd** [comment]
Thanks for figuring this out.

**Comment by laxminair** [comment]
How did you modify the file? Even when I manage to edit the file (C-x C-q on emacs) I can't save it. How did you over write the permissions?

**Comment by john-guerra** [comment]
You have to do it with the user root

$ sudo emacs filename

Should do the trick (If you have sudo permissions) or

$ su
(root password)
Then
# emacs filename

John

**Comment by ayman** [comment]
While this is a fair work around, it causes me an issue running python27 installed via MacPorts.  Specifically, the prompt fails to print color codes correctly:

```[[1mpsiTurk[0m server:[91moff[0m mode:[1msdbx[0m #HITs:0]$```

Which seems to be related to ```cmd2.py``` where at line 906 we find:

```python
            try:
                import readline
                self.old_completer = readline.get_completer()
                readline.set_completer(self.complete)
                readline.parse_and_bind(self.completekey+": complete")
```

if I edit the import here to read ```import gnureadline as readline``` then the color prompt renders correctly.  However we've left the scope of psiturk to make an edit.  I suppose the ```_cmdloop``` could be overridden in ```psiturk_shell.py```.

**Comment by dbirman** [comment]
This problem still appears for some users by the way, appears to be an OS X specific problem, might be worth seeing whether the change can be merged at this point...

**Comment by deargle** [comment]
Ha, I just helped a friend with this not two hours ago.

I don't have a mac, so can someone test this for me at line 21?

``` python
try:
    import gnureadline as readline
except ImportError:
    import readline
```

**Comment by deargle** [comment]
Who needs testing! Merged. Would be nice if some other PC and mac users could pull down @master and test against that before I create a tag, though.

**Comment by deargle** [comment]
Made a minor release anyways (v2.1.7) because yolo.

**Comment by gureckis** [comment]
:+1:, were you able to push it to pip?

**Comment by deargle** [comment]
[Yup](https://pypi.python.org/pypi/PsiTurk/2.1.7), thanks to good old Travis CI.
