### ISSUE TITLE
psiturk exits even when told not to

### ISSUE THREAD

**Issue by RoyalTS** [NYUCCL/psiTurk#174]
With a server running, if I give psiturk the `exit` command I get the 

    Quitting shell will shut down experiment server. Really quit? y or n:

prompt. As I've just discovered psiturk will shut down irrespective of whether I then type in `y` or `n`. Looking at the code that handles this it's not immediately obvious to me why it would do that, but at least on my machine it does.

**Comment by gureckis** [comment]
I think I fixed this is the dev branch... https://github.com/NYUCCL/psiTurk/commit/c4c4958dc326e53ea3b1ac4421c92279ed541eb2

**Comment by RoyalTS** [comment]
Ah, yes, that fixes it. Thanks!
