### ISSUE TITLE
Contribute features from Wallace back into psiTurk

### ISSUE THREAD

**Issue by suchow** [NYUCCL/psiTurk#180]
In the process of creating Wallace, an experimental platform for simulating cultural evolution online, we've made a number of improvements and extensions to psiTurk. I've opened this issue to start a conversation about what you'd be interested in us contributing back to psiTurk proper.

Here's what we've done:
- [ ] Make it possible to run psiTurk on Heroku
- [x] Improve install speed by installing gnureadline only on OS X
- [x] Allow longer HTTP requests
- [x] Create a route that receives  REST notifications from Amazon about HIT-related events
- [x] Create "HIT types" when creating new HITs.
- [x] Allow HIT durations that are < 1 hr.

@jhamrick, @thomasmorgan, @michaelpacer, @smeylan.

**Comment by jhamrick** [comment]
I think the second is already done in #158.

**Comment by twiecki** [comment]
Heroku definitely would make deployment easier.

**Comment by gureckis** [comment]
This all sounds pretty awesome.  I think any/all of these could hit be good pull requests.  One question thought: why is Heroku easier than say OpenShift or AWS?

**Comment by suchow** [comment]
Okay, that pull request has everything except for Heroku support, which I'll do separately — I may need to work on it a bit to make it automatically detect if you're on Heroku and run that code conditionally.

**Comment by mshvartsman** [comment]
+1 for sub-1hr HITs. I think this makes it clearer to worker that the task we give them shouldn't take very long (and therefore is worth doing for the relatively small amount of $ we pay). 

I implemented one way of doing this in https://github.com/mshvartsman/psiTurk/tree/180-sub-hour-tasks. Integers passed in still get read as hours, but `hours:minutes` gets parsed. 

Should I submit a pull request? Should I do it against dev as per the contrib guidelines or master as per #193?

**Comment by andrewheusser** [comment]
@suchow: was heroku support added or did that not make it in?

**Comment by suchow** [comment]
@andrewheusser 

I'm going to close this now because everything on the original list is finished except for Heroku support. A first draft of that support is implemented in https://github.com/suchow/psiTurk-heroku, though I'm not sure how those changes interact with other services that people use to run psiTurk.
