### ISSUE TITLE
Bonus Fails

### ISSUE THREAD

**Issue by jacob-lee** [NYUCCL/psiTurk#190]
It occasionally happens that a worker finishes a psiturk task, but fails to "complete" the HIT. Then another worker will take up the assignment and complete the HIT. The result is that there will be two records in the database with the same assignment ID, but with different worker IDs. In this case, attempts to bonus the second worker may fail, although they were successfully approved.

It looks like amt_services.bonus_worker pulls the first record with that assignment id, and fetches the associated worker_id:

```
assignment = self.mtc.get_assignment(assignment_id)[0]
worker_id = assignment.WorkerId
self.mtc.grant_bonus(worker_id, assignment_id, bonus, reason)
```

If the first record fetched is the wrong one, it would, presumably, raise an Exception since the worker_id and assignment_id are not paired with respect to awt. Changing the assignment ID, or deleting one of the records resolves the issue, confirming diagnosis.

**Comment by mshvartsman** [comment]
Confirming that I just ran into this as well.

**Comment by deargle** [comment]
@jacob-lee @mshvartsman Looks like the culprit code is [here](https://github.com/NYUCCL/psiTurk/blob/376fed73e0ee44591b8b8048576478332d96e46f/psiturk/psiturk_shell.py#L740)

It should check that Participant.status >= 4 (submitted)

**Comment by jacob-lee** [comment]
Actually, I've encountered situations in which two participants with status=4 have the same assignment ID in the db. This can happen, apparently, if a subject submits the 'complete hit', but reloads the page immediately after (e.g. if the response is too slow).

**Comment by deargle** [comment]
Oh wow yeah I see. The `thanks.html` version _on the psiturk.org server_ does this (I think):

    <script>
        function complete_amt_task() {
            // reload trials
            $.ajax({
                dataType: "json",
                type: "GET",
                url: "/worker_submitted?uniqueId={{ workerid }}:{{ assignmentid }}",
                success: function (data) {
                    $( "#mturk_form" ).submit();
                }
            });
        };
    </script>

So you're saying `/worker_submitted` gets called and their status gets set to `submitted` in the psiturk db, but they refresh before the `success` and consequent mturk form `submit()` is called... and when they reload the page, their status won't be something psiturk knows how to handle since it'll be greater than COMPLETED, so it'll hit the ["status incorrectly set" error here.](https://github.com/NYUCCL/psiTurk/blob/master/psiturk/experiment.py#L296)

What can be done? Off the cuff thoughts: 

1. block them from refreshing the page while the `/worker_submitted` request response is pending
2. have experiment.py do its own form submission to mturk if 
    - they are viewing the ad
    - not `already_in_db` for another assignment_id, and 
    - if their `status==submitted`

**Comment by deargle** [comment]
Here's a solution using approach No. 1. It binds and unbinds an onbeforeunload event. @gureckis I tested it on my no-ad-server branch using my `thanks-mturksubmit.html` template and it works. I'll add this to that PR, could you add it to the psiturk.org ad server? 

The PR associated with this issue (#210) would still be good to pull.

        function complete_amt_task() {
            $(window).on('beforeunload', function(){
                return 'Your submission is in progress. If you leave now, your assignment data will be corrupted.';
            });
            $.ajax({
                dataType: "json",
                type: "GET",
                url: "/worker_submitted?uniqueId={{ workerid }}:{{ assignmentid }}",
                success: function (data) {
                    $( "#mturk_form" ).submit();
                    $(window).off('beforeunload');
                }
            });
        };

**Comment by gureckis** [comment]
so should i update the ad servers (sandbox,live) to include this revised `complete_amt_task`?

**Comment by deargle** [comment]
I vote yea. It's a good safeguard. If they ignore the prompt they'll still
get corrupted data, but this should at least cut down on that happening. I
recently put a PR on ad.psiturk.org repo that does this update.

**Comment by gureckis** [comment]
Ok, just processed this thread.  I think the message "your assignment data will be corrupted" is a little ambiguous from the perspective of a unsophisticated worker.  Maybe "Your submission is in progress.  Please do not close this window."  ?

**Comment by deargle** [comment]
Sure, good point. I'll edit the ad.psiturk.org PR and I'll edit it here too.

**Comment by deargle** [comment]
Done and done.

**Comment by gureckis** [comment]
👍

**Comment by gureckis** [comment]
ok this should be propogated to sandbox.ad.psiturk.prg and ad.psiturk.org

**Comment by deargle** [comment]
Long Live Psiturk
