### ISSUE TITLE
dealing with pull requests (dev, master)

### ISSUE THREAD

**Issue by gureckis** [NYUCCL/psiTurk#193]
Hi all,

When we set psiTurk up on Github it was recommended that we make the `master` branch sync with pypi and use `dev` for ongoing development.  I propose flipping this starting tomorrow:  `master` will be the new `dev` branch. This is helpful since github by default targets pull requests to `master`.  Almost every pull request we get goes to `master` and then either the requester has to recreate it or we have to manually merge it into `dev`.

Instead, when new releases come out we will make a branch for the new release and push that to pypi and then update the readthedocs to pull from the correct branch.

Speak up with any objections or suggestions otherwise I'll try to update the relevant docs and do this.

thanks,
t

**Comment by jhamrick** [comment]
:+1: on this. I think the workflow where `master` is actually the development branch is much easier for newcomers and people with experience alike. Having different branches for each release also makes it much more convenient (in my opinion) for doing things like backporting bugfix PRs -- that way a fix can go into master, but also onto a release branch. This is how IPython does it, e.g., IPython 3.0.0 will be released but then a bunch of bugfixes will be made to master and backported to the 3.x branch and so eventually 3.1.0 is released with those fixes.

**Comment by gureckis** [comment]
master is now 'dev'.  dev will be retired soon.  we will use branches to track numbered releases which are distributed via pypi.  this should speed up the rate at which new patches are merged into the project.
