### ISSUE TITLE
multiple processes on same server by different users 

### ISSUE THREAD

**Issue by annacoenen** [NYUCCL/psiTurk#197]
Currently "is_server_running" in experiment_server_controller.py checks for all current psiturk processes (including by other users and other ports), and so only one person at a time can run psiturk off the same server. Can we somehow filter processes uniquely by users in that function?

**Comment by Wildcarde** [comment]
Ideally, a single user should be able to run multiple experiments as well as long as they are on different ports.

**Comment by deargle** [comment]
I think this is possible now.
