### ISSUE TITLE
recordUnstructuredData Doesn't Override Existing Data

### ISSUE THREAD

**Issue by dbirman** [NYUCCL/psiTurk#199]
I'm trying to set up my task to record an unstructured xml object after every block to avoid potential data loss. But repeated calls to recordUnstructuredData do not appear to overwrite the existing object. I looked through the code and I can't figure out why this wouldn't be the case. My data objects are fairly large so I don't want to save multiple copies, any idea why the xml field isn't being overwritten?

```
	myscreen.psiTurk.recordUnstructuredData("experimentXML", xml);
	myscreen.psiTurk.saveData();
```

**Comment by gureckis** [comment]
by default psiturk.js already re-saves all your data on each saveData() call.
the concept is that you use recordUnstructuredData() or recordTrialData() to save a single
trial or line to your file.  (more like a push-down stack which is synchronized to the server
each time saveData() is called).

so basically we were already doing for you what you are trying here.
i guess you can look at psiturk.js to override our saveData() mechanism for your own purposes
or just save bits of XML at a time and let psiturk.js handle the synchronization of all the data each
time it saves.

**Comment by dbirman** [comment]
Okay yeah I think that the way we're saving data has to override the functionality then. Thanks for explaining this!
