### ISSUE TITLE
Roadmap for allowing public psiTurk signups?

### ISSUE THREAD

**Issue by suchow** [NYUCCL/psiTurk#200]
Hi all — we've built [Wallace](https://github.com/suchow/Wallace), a platform for experimentation on cultural evolution etc. on top of psiTurk. We've started to show Wallace to some collaborators, who have been unable to get started because they can't signup for a psiTurk account. It used to be that requesting an invite was a formality, immediately sending an invite. But not any more. This is worrying. What's the plan for scaling up to public use of psiTurk? Is there anything we can do to help?

cc @jhamrick @thomasmorgan

**Comment by gureckis** [comment]
sorry i increased the number allowed to 750 today… the original limit was 500 out of concern the system might not scale well under heavy load
however, so far it’s been ok (knock on wood)

so, everyone should be ok.  if you signed up and didn’t get the confirmation email let me know and i’ll reset your account name so you can sign up again.

**Comment by suchow** [comment]
great thanks!

-- 
Jordan Suchow
http://suchow.io
