### ISSUE TITLE
Haven't received psiturk invitation

### ISSUE THREAD

**Issue by ghost** [NYUCCL/psiTurk#202]
I requested an invitation a few days ago, and haven't yet received one. I've checked, and there's nothing in my spam folders. How long does it usually take to get an account? Thanks!

**Comment by Speldosa** [comment]
I guess there's no point in keeping a two year old support request as an open issue. Shouldn't this be closed?

**Comment by deargle** [comment]
We were keeping it around for nostalgia, but I suppose a little spring cleaning won't hurt.
