### ISSUE TITLE
worker list returning limited list, affecting bonuses

### ISSUE THREAD

**Issue by agardony** [NYUCCL/psiTurk#203]
I recently ran a HIT in which I was bonusing participants en masse. The n of the study is 119 now but when I run:

worker list --hit [HITID] 

it only returns the first 100 workers. I tested this with some old 100+ participated HITs we had and noticed the same problem. Only the first 100 workers are returned.

Further in our recent study when I try to bonus the 101st and above participants I am unable to. I currently have 19 participants I will need to bonus manually. I was using worker bonus --amount [amount] --hit [HITID] to do this but since it only reads the first 100 participants it is unable to bonus them.

Looking at the worker list source code it looks like the list is pulled amazon's amt_services. Is there currently an issue in accessing worker lists from amazon?

**Comment by deargle** [comment]
@agardony I don't have a worker list large enough to test this myself, but try bumping up page_size to be greater than 100 in amt_services.py, line 404

**Comment by agardony** [comment]
@deargle Thanks for the help. I tried what you said upping to 1000 and also to 101. In both cases got the following error when I tried to list workers for my HIT.

*** failed to get workers
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/cmd2.py", line 788, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "build/bdist.linux-x86_64/egg/cmd2.py", line 871, in onecmd
    stop = func(statement)
  File "/Library/Python/2.7/site-packages/PsiTurk-2.1.1-py2.7.egg/psiturk/psiturk_shell.py", line 87, in helper_fn
    return func(self, opt)
  File "/Library/Python/2.7/site-packages/PsiTurk-2.1.1-py2.7.egg/psiturk/psiturk_shell.py", line 1607, in do_worker
    arg['--rejected'], arg['<hit_id>'])
  File "/Library/Python/2.7/site-packages/PsiTurk-2.1.1-py2.7.egg/psiturk/psiturk_shell.py", line 627, in worker_list
    workers = [worker for worker in workers if \
TypeError: 'bool' object is not iterable
'bool' object is not iterable

**Comment by deargle** [comment]
@agardony Indeed. get_workers calls boto's get_assignments, which calls AWS's GetAssignmentsForHit. Acceptable values for PageSize are [1 to 100](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_GetAssignmentsForHITOperation.html)

I'm not sure the best way to go about this, but one way around this is to pass a different page_number to boto's get_assignments (defaults to the first page).

**Comment by deargle** [comment]
@agardony check out PR #207, it has a fix for this issue.
