### ISSUE TITLE
building docs, extension error: config value 'math_number_all' already present

### ISSUE THREAD

**Issue by deargle** [NYUCCL/psiTurk#222]
psiturk's sphinx config loads pngmath and mathjax. as of sphinx 1.4 (i think) pngmath has been deprecated and imgmath has taken its place. See [here](http://www.sphinx-doc.org/en/stable/ext/math.html#module-sphinx.ext.imgmath). When I try to build the docs I get a 'math_number_all' error message and they won't build, even if I replace pngmath with imgmath in the config. commenting out the imgmath extension allows the docs to build. But I'm a noob with sphinx so I don't know if imgmath would be preferred over mathjax. I assume it's either-or. I think the docs are pushing imgmath.

**Comment by gureckis** [comment]
i'll try removing imgmath.  i'm not sure the docs use any math typesetting actually.

**Comment by gureckis** [comment]
this seemed to work, thanks
