### ISSUE TITLE
Requirements should be updated?

### ISSUE THREAD

**Issue by cjbates-mit** [NYUCCL/psiTurk#234]
I just did the pip install and I had to additionally install the following in order to start the psiturk server:

sudo pip install click
sudo pip install jinja2
sudo pip install werkzeug
sudo pip install itsdangerous

**Comment by deargle** [comment]
That's unusual, those should already be installed along with psiturk. I
notice you are installing with sudo -- Try installing into a new virtualenv
and see how things go for you? (Check out virtualenvwrapper.) Works fine
for me.

**Comment by cjbates-mit** [comment]
Weird. It worked with virtualenv on Mac OS X. (I had done it on an ec2 ubuntu 14.04 instance when it didn't work).

**Comment by deargle** [comment]
Bizarre.
