### ISSUE TITLE
us_only and approve_requirement in configuration file have no effect

### ISSUE THREAD

**Issue by chepner3** [NYUCCL/psiTurk#263]
I have been running experiments with `us_only = true` and `approve_requirement = 95` set in the local configuration file.  Since I was getting a significant number of participants from outside the US, I checked the qualification requirements for the HITs I had posted using PsiTurk and discovered that there were no qualification requirements listed for any of them.  The other parameters set in the configuration file (`title`, `description`, `lifetime`, etc.) all seem to be working as expected, so the issue does not seem to be a missing or misplaced configuration file.

Am I doing something wrong with my configuration files, or is this a bug?

Someone else seems to have had the same issue recently as well: [https://groups.google.com/d/msg/psiturk/5P7lXYkjSkY/_HudtSSoAgAJ](https://groups.google.com/d/msg/psiturk/5P7lXYkjSkY/_HudtSSoAgAJ).

**Comment by chepner3** [comment]
I think I may have figured out what is causing this.  The documentation for the CreateHIT operation in the Mechanical Turk API (see [http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateHITOperation.html](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateHITOperation.html)) states:

"If the HITTypeId parameter is specified, the CreateHIT operation assumes the syntax with a HIT type ID is what you intended. If you provide both a HIT type ID and values for the common properties, the common property values are ignored."

When a HIT is configured in `configure_hit()` in amt_services.py, **both** the HITTypeId **and** the common properties are specified.  The qualification requirements are not included in the HIT type specification, so they are ignored even though they are included in the HIT parameters.

I am not very familiar with the way boto or amt_services.py work, but it looks to me like this could be fixed by changing `qual_req=None` to `qual_req=quals` on line [543](https://github.com/NYUCCL/psiTurk/blob/master/psiturk/amt_services.py#L543).

**Comment by deargle** [comment]
Egads. Were you able to test if your fix works? I'll try to find time soon.

**Comment by deargle** [comment]
[Here's](https://github.com/boto/boto/blob/2af51cd07d2b8be5d5868a3d368dc45566c74ecc/boto/mturk/connection.py#L76) the part in Boto where qual_req is processed (default None). It looks like it doesn't use it during the creation of the HIT type if it's None. So it's as if it's not specified in the Hit Type, and therefore we're only specifying the common properties? More testing required.

**Comment by chepner3** [comment]
I have had a chance to test my fix, and it seems to have worked.  Setting `us_only = true` and `approve_requirement = 95` now causes new HITs to have the appropriate qualification requirements, at least in the sandbox.

**Comment by deargle** [comment]
I'm still weirded out that this has been this way for so long. I am looking into what else is affected. So far, I've learned that these fields are the "common property values" that are included in the hit type id (and therefore ignored when reset again later): 

```
Properties of a HIT Type

The HIT properties that define a HIT type are the following:

* Title
* Description
* Keywords
* Reward
* AssignmentDurationInSeconds
* AutoApprovalDelayInSeconds
* A set of zero or more QualificationRequirements
```
([source](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMechanicalTurkRequester/Concepts_HITTypesArticle.html))

For reference, 
[right here in this params_dict](https://github.com/NYUCCL/psiTurk/blob/d00b5718c4a39277578d34e1b1c145cda606d84a/psiturk/amt_services.py#L570) psiturk passes a hit id and sets several property values:

``` python
        self.param_dict = dict(
            hit_type=hit_type.HITTypeId,
            question=mturk_question,
            lifetime=hit_config['lifetime'],
            max_assignments=hit_config['max_assignments'],
            title=hit_config['title'],
            description=hit_config['description'],
            keywords=hit_config['keywords'],
            reward=hit_config['reward'],
            duration=hit_config['duration'],
            approval_delay=None,
            questions=None,
            qualifications=quals,
            response_groups=[
                'Minimal',
                'HITDetail',
                'HITQuestion',
                'HITAssignmentSummary'
            ])
```
Which means that the following parameters should be ignored in that params_dict:

* title
* description
* keywords
* reward
* duration
* approval_delay
* __qualifications__

And these are the ones that can stay in the params_dict:

```
Properties Specific to a HIT

HITs of the same HIT type can have differing values for the following properties:

* Question
* MaxAssignments
* LifetimeInSeconds
* RequesterAnnotation

([source, at the bottom](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMechanicalTurkRequester/Concepts_HITTypesArticle.html))


This might mean that it's a bug in boto to allow qualifications to be passed even when HITTypeID is also passed ([here](https://github.com/boto/boto/blob/2af51cd07d2b8be5d5868a3d368dc45566c74ecc/boto/mturk/connection.py#L224-L258))

Indeed, just found that [it's been a bug since 2013](https://github.com/boto/boto/issues/1678). Argh!

**Comment by gureckis** [comment]
oh jeez.  well, honestly this just reinforces to me why open-source is better for this type of thing.  bugs get caught that in an individual lab might linger for a long time!
