### ISSUE TITLE
example experiment flow

### ISSUE THREAD

**Issue by braingineer** [NYUCCL/psiTurk#267]
Hello,

I was just wondering how committed you all were to using the experiment in the example folder.  I recently had to pick through someone's implementation and tracing the flow was very.. frustrating.  It was all due to the convention of burying the experiment design in the experiment itself (e.g. [this](https://github.com/NYUCCL/psiTurk/blob/master/psiturk/example/static/js/task.js#L195)). 

I've been working with jspsych for a while with psiturk and really like the top-level timeline design.  Is there a commitment to being dependency free and that's why jspsych isn't used?

**Comment by gureckis** [comment]
no, another version could be cool.  I’m not sure what you mean about the design being buried in the experiment itself (and the showPage()) call.
can you unpack what is confusing and how the jspsych is easier?

**Comment by braingineer** [comment]
Awesome!  I will PR it when psiturk stuff cycles back to the foreground.  

The example in the repo isn't as bad as the encounter I had, so the pattern I'm going to point at isn't all that horrible.  Taken further though by having several objects in one experiment and it becomes very cumbersome. 

Tracing through the experiment flow:

1. Code loads in `task.js`
2. Hits [this part and start the instructions](https://github.com/NYUCCL/psiTurk/blob/master/psiturk/example/static/js/task.js#L219)
3. In that same part, `StroopExperiment` is declared to be the thing that follows the instructions. 
4. `StroopExperiment` runs, [shows a page, called an intro function `next`](https://github.com/NYUCCL/psiTurk/blob/master/psiturk/example/static/js/task.js#L144)
5. `next` controls the logic for stimuli, [calls `finish` when done](https://github.com/NYUCCL/psiTurk/blob/master/psiturk/example/static/js/task.js#L67)
6. [`finish` declares next function](https://github.com/NYUCCL/psiTurk/blob/master/psiturk/example/static/js/task.js#L121), `Questionnaire`


This pattern, extrapolated to multiple modules, means that you have to trace through each module to figure out (1) what it does per trial, (2) when it finishes, and (3) where it's going after that.  Also, if the person has any additional bad coding habits, it becomes accentuated the structure of the implementation doesn't give a ton of clues as to where things should be. For instance, they don't **have** to use the function names `next` and `finish`.  in my experience, when people can muck up their code, they will (murphy's law of software engineering?)

Anyway, that's really the whole reason: you have to trace through the implementation to document what is going to happen when.  

After I catch up on some stuff, I'll push on getting a basic implementation and PR it. It's part of my stack of things to do anyway---I'm trying to make a default model evaluation structure for some colleagues.

**Comment by gureckis** [comment]
Yeah, I think the structure was design so that there was a kind of “object” associated with each phase of the
task.  This made things somewhat modular because you could pull out the module for one part of the task
and move it to another experiment without needing to know the details of what is happening inside the module.
However, if you have a better method that also favors reuse then please share.  One of the ideas of psiTurk is
to enable the sharing of “best practices” in the community!
T

**Comment by deargle** [comment]
Stale
