### ISSUE TITLE
Bump requests version

### ISSUE THREAD

**Issue by ariekahn** [NYUCCL/psiTurk#269]
Running into the following issue, which basically amounts to the version of urllib3 bundled with requests` not handling openssl when not compiled with SSLv3 support (which I'm running into on EC2):
http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

Should requests get updated? It's pinned at a pretty ancient version right now, and it looks like fix is in 2.5 onwards.
https://github.com/kennethreitz/requests/commit/7aa6c62d6d917e11f81b166d1d6c9e60340783ac

**Comment by deargle** [comment]
Sure, we can upgrade requests. Meanwhile, does upgrading pip fix your problem on EC2, as suggested lower in that SO post?

**Comment by ariekahn** [comment]
pip's getting upgraded beforehand:
```
$ pip -V
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

I've been manually upgrading requests up until now, which works fine with the copy on pypi, so was just ignoring this.
E.g. the following runs fine:
```
pip install psiturk==2.2.1
pip install -U requests
```

However, when I try to install from the github copy, e.g. 
```
pip install git+https://github.com/NYUCCL/psiTurk.git@2.2.1
pip install -U requests
```
I get
```
/psiturk$ psiturk
Traceback (most recent call last):
  File "/usr/local/bin/psiturk", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests==2.2.1' distribution was not found and is required by PsiTurk
```

Any idea why there'd be a difference?

**Comment by deargle** [comment]
No idea. The copy on pypi is put there automagically by Travis CI, so they should be exactly the same...

**Comment by deargle** [comment]
I get insecure platform warnings on >=2.6.0, and I'm lazy, so 2.5 it is.

**Comment by deargle** [comment]
@ariekahn can you confirm that this fixes your issue?

**Comment by deargle** [comment]
In response to this:

> Any idea why there'd be a difference?

I just tested, and installing via pypi dist does not install an egg into site-packages (only a .dist), and therefore does not include a `requires.txt`. It's the `requires.txt` in the egg (which is present when installing via github, through pip) which enforces the pinned version requirements.

I'm a novice in the land of python eggs and dists, though.

**Comment by ariekahn** [comment]
@deargle Yep, that fixed it!

And just noticed the difference in installation methods, thanks for looking into it.
