### ISSUE TITLE
language detection does not work in recent versions of most browsers

### ISSUE THREAD

**Issue by chepner3** [NYUCCL/psiTurk#270]
PsiTurk currently attempts to detect a participant's language based on the user agent string (see [experiment.py line 408](https://github.com/NYUCCL/psiTurk/blob/master/psiturk/experiment.py#L408)).  Recent versions of most browsers no longer include language preferences in the user agent string, so this method does not work reliably.

A better way to do this would be to use the [Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) HTTP header instead of the [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) header.  It contains a list of languages the browser will accept and a preference weighting for each one, based on the user's language settings.  The full list of languages the browser will accept can be accessed using `request.accept_languages`.  The most preferred language can be accessed using `request.accept_languages.best`, which would replicate the original behavior of the language detection feature.

**Comment by gureckis** [comment]
sounds like a simple pull request... but seems like it was reverted?

**Comment by deargle** [comment]
I'm curious what will happen if a not-recent-enough browser is used. I
didn't see compatibility versioning info on mdn. Would probably be best to
have a fallback or safety check lest a js explosion happens. Although I
guess worst-case is an undefined.

**Comment by chepner3** [comment]
Sorry, I am a bit new to git; I seem to have reverted the pull request by accident.  I have been using the code included in the pull request for a month or so now, and it has worked 100% of the time so far.

The Accept-Language HTTP header has been a standard since the first HTTP/1.1 specification in 1997.  The MDN compatibility table shows "yes" with no further clarification about version numbers because common use of this header predates all of the browsers listed, except maybe Internet Explorer.  Most modern browsers would have included support for the Accept-Language header in their initial release.
