### ISSUE TITLE
Cannot create a hit in sandbox mode

### ISSUE THREAD

**Issue by PatrickLaflamme** [NYUCCL/psiTurk#275]
I can't seem to get psiturk to create a test hit. Unfortunately I keep getting this error:

```
*****************************
  Sorry, there was an error creating hit and registering ad.
  Unable to create HIT on Amazon Mechanical Turk.
```

I checked the server log, and nothing was written to it, so I'm no quite sure how to start debugging.

**Comment by deargle** [comment]
Unfortunately there's a lot of things that could have gone wrong. Share your config.txt?

**Comment by PatrickLaflamme** [comment]
Sorry about that, here it is.

```

[HIT Configuration]
title = unknown
description = Respond as quickly as you can
amt_keywords = Perception, Psychology, experiment
lifetime = 24
us_only = true
approve_requirement = 95
contact_email_on_error = patrick.laflamme@psych.ubc.ca
ad_group = jspsych simple experiment example
psiturk_keywords = reaction time
organization_name = New Great University
browser_exclude_rule = MSIE, mobile, tablet

[Database Parameters]
#database_url = mysql://<<myUsernameHere>>:<<PSWD>>@<<IP ADDRESS>>:3306/<<DATABASE>>
database_url = sqlite:///participants.db
table_name = turkdemo

[Server Parameters]
host = 0.0.0.0
port = 22362
cutoff_time = 30
logfile = server.log
loglevel = 2
debug = true
login_username = examplename
login_pw = examplepassword
threads = auto

[Task Parameters]
experiment_code_version = 1.0
num_conds = 1
num_counters = 2

[Shell Parameters]
launch_in_sandbox_mode = true

```

My mysql database is working, I've checked, but I removed the info from my post for obvious reasons.

**Comment by deargle** [comment]
Looks okay. Are you comfortable editing your psiturk source? I'd like to see a printout of hit_config ([right here](https://github.com/NYUCCL/psiTurk/blob/b86ef13cda5f981f244876fe8a156a25a9eeb755/psiturk/psiturk_shell.py#L1173))

If not, what are you passing when you run `hit create` for numWorkers, reward, and duration?

**Comment by PatrickLaflamme** [comment]
I can do that! Here is a printout of hit_config

```
{'duration': datetime.timedelta(0, 3600), 'reward': 0.0, 'description': 'Respond as quickly as you can', 'max_assignments': 1, 'lifetime': datetime.timedelta(1), 'keywords': 'Perception, Psychology, experiment', 'approve_requirement': '95', 'title': 'unknown', 'ad_location': 'https://sandbox.ad.psiturk.org/view/ij96ajMv6We9mjS8HaYPRH', 'us_only': True}
```

**Comment by PatrickLaflamme** [comment]
After some investigation, it appears that you need to activate the sandbox mode of MTurk separately from live MTurk (apparently they are technically two separate accounts). I activated the sandbox mode of MTurk on my account, and it works like a charm!

Thanks!
