### ISSUE TITLE
revproxy_url without default port

### ISSUE THREAD

**Issue by yeonsoonshin** [NYUCCL/psiTurk#276]
Thank you for implementing reverse proxy support in the newest version of psiturk!

I found that revproxy url is currently formatted as 
`revproxy_url = "http://{}:{}/ad".format(self.config.get('Server Parameters', 
                                                                    'adserver_revproxy_host'), port).`
However, this prevents my host from working correctly, because my `adserver_revproxy_host` is set to 
`https://xxx.edu/app01/`
so the `revproxy_url` ends up being `https://xxx.edu/app01:80`, while what I would need is `http://xxx.edu:80/app01`

Would it be possible to make it something like:
`revproxy_url = "http://{}/ad".format(self.config.get('Server Parameters', 
                                                                    'adserver_revproxy_host')).`
and we can just manually put port number within the host url? 

Thank you!

**Comment by deargle** [comment]
I suspect that running a psiturk experiment off of a subdirectory would require refactoring a lot more than just this area of code. You can try it out though by forking?

**Comment by yeonsoonshin** [comment]
I could edit [`do_debug` part](https://github.com/NYUCCL/psiTurk/blob/b86ef13cda5f981f244876fe8a156a25a9eeb755/psiturk/psiturk_shell.py#L1796) that I mentioned above, but I think the import work that actually sends information to ad server is done [here](https://github.com/NYUCCL/psiTurk/blob/b86ef13cda5f981f244876fe8a156a25a9eeb755/psiturk/psiturk_shell.py#L1127) in `create_psiturk_ad `.  Would there be any way that ad server parses the information differently (i assume that it currently uses the format such as `http://{}:{}/ad`)?

**Comment by deargle** [comment]
Ah yes, it will break there. That would be a non-backwards-compatible change to the ad server, so it would take some careful work before implementing. Probably the fastest option for you if you really must be able to serve off of a subdirectory will be to fork and not use the ad server.

**Comment by deargle** [comment]
Closing because stale
