### ISSUE TITLE
increase gunicorn timeout to avoid worker timeout

### ISSUE THREAD

**Issue by andrewheusser** [NYUCCL/psiTurk#285]
I have a rather complicated experiment where I've written multiple custom routes that happen between blocks in the experiment.  One of the processes can sometimes take > 30 seconds to return an answer, and I'm running into an issue where the psiturk server seems to stop responding when this happens (at least, I think this is the issue).  The error returned in the server log is: 

`[28] [CRITICAL] WORKER TIMEOUT (pid:32)`

I dug into the gunicorn documentation a little bit, and found that its possible to manually change the timeout duration with the timeout flag ([link](http://docs.gunicorn.org/en/stable/settings.html#timeout))

To expose this argument, I was thinking about modifying [these lines](https://github.com/NYUCCL/psiTurk/blob/master/psiturk/experiment_server.py#L67) of the  `experiment_server.py` file by adding the timeout flag like this:

```
        self.user_options = {
            'timeout': config.get("Server Parameters", "timeout"), ## <- add this line
            'bind': config.get("Server Parameters", "host") + ":" + config.get("Server Parameters", "port"),
            'workers': workers,
            'loglevels': self.loglevels,
            'loglevel': self.loglevels[config.getint("Server Parameters", "loglevel")],
            # 'accesslog': config.get("Server Parameters", "logfile"),
            'errorlog': config.get("Server Parameters", "logfile"),
            'proc_name': 'psiturk_experiment_server',
            'limit_request_line': '0',
            'on_exit': on_exit
        }
```

I was wondering if someone with more expertise with psiturk might be able to tell me if this is reasonable, or a terrible idea.  Or is it already possible to modify the gunicorn `timeout` parameter within psiturk, and I just missed it?  Any advice would be greatly appreciated (and let me know if you need additional info)!

**Comment by deargle** [comment]
Seems like your idea should work. Does it? Although you'll want to do `config.getint("Server Parameters", "timeout")` instead. What are you going to set it to? 

Note that this may bind up your server -- it currently uses sync workers. I'm not sure what exactly that will mean for your experiment, but try somehow to see how many workers you can have going through your task at once before things break.

**Comment by deargle** [comment]
See [this old issue](https://github.com/NYUCCL/psiTurk/issues/73) and the referenced branch

**Comment by andrewheusser** [comment]
Thanks for the comments @deargle .  I'm going to try 1 minute, as the computation I'm running should be done never take longer than that (but it can take more than 30 seconds).

I think it should be ok to lock up the server for now.  I am running the experiment on a single lab computer with only one subject at a time.  The computation has to complete before moving on to the next block, and nothing is happening on the screen at that time. Once we move it to the web, I'm going to wrap each experiment instance in a docker container and spawn them on a cluster as needed.  

Will keep you posted on whether I'm successful with increasing the gunicorn timeout.

**Comment by andrewheusser** [comment]
Hi @deargle - I added the `timeout` parameter to the `ExperimentServer.user_options` dict and then `timeout = 60` to the config.txt file.  The program doesn't crash, but I'm not sure how to verify it actually changed the parameter.  Any ideas? Thank you!

**Comment by andrewheusser** [comment]
The code is here: https://github.com/ContextLab/psiTurk/blob/expose-gunicorn-timeout-parameter/psiturk/experiment_server.py#L76

**Comment by andrewheusser** [comment]
great, thanks for taking a look :)  That's a good idea, I'll give it a try!

**Comment by andrewheusser** [comment]
great, that seems to have fixed my issue! not sure if this param would be useful to others, but happy to submit a PR if you think it is

**Comment by deargle** [comment]
Couldn't hurt. Can you also add something to the docs for it, including a
use case (long api calls in routes in custom.py)?
