### ISSUE TITLE
public access not possible when setting server to 0.0.0.0

### ISSUE THREAD

**Issue by zahybnaya** [NYUCCL/psiTurk#288]
I can access psiturk locally, but can't from outside the machine. 
Made sure it's not a firewall issues (a different service works fine on the same port). 
According to the docs I understand that I'm all set (setting host to 0.0.0.0), what am I missing?

```
[psiTurk server:on mode:sdbx #HITs:1]$ config print

[AWS Access]
aws_region=us-east-1
aws_access_key_id=xxx
aws_secret_access_key=xxx

[psiTurk Access]
psiturk_secret_access_id=xxxx
psiturk_access_key_id=xxx

[HIT Configuration]
description=mytask
title=task
browser_exclude_rule=MSIE, mobile, tablet
us_only=true
psiturk_keywords=Rushhour
organization_name=New York University
ad_group=Default psiTurk Rushhour  Example
contact_email_on_error=email@nyu.edu
allow_repeats=false
lifetime=24
approve_requirement=95
amt_keywords=Psychology

[Database Parameters]
database_url=sqlite:///participants.db
table_name=rushhour

[Server Parameters]
loglevel=2
login_pw=examplepassword
login_username=examplename
host=0.0.0.0
threads=auto
cutoff_time=30
debug=false
secret_key='this is my secret key which is hard to guess, i should change this'
logfile=server.log
port=5001

[Task Parameters]
num_counters=1
experiment_code_version=1.0
num_conds=1

[Shell Parameters]
launch_in_sandbox_mode=true
ad_location=false
use_psiturk_ad_server=false  
```

**Comment by zahybnaya** [comment]
Same behavior when I'm using the psiturk-setup-example (and changing the hostname and port).

**Comment by deargle** [comment]
If you set use_psiturk_ad_server to false, you have to set ad_location

Not sure if that's your issue though.

**Comment by zahybnaya** [comment]
It is not. 

Also used 
```
ad_location=true
use_psiturk_ad_server=false  
```

**Comment by deargle** [comment]
That's not right usage either, read the docs. On mobile or I'd help more.

**Comment by zahybnaya** [comment]
Sorry, I meant the other way around. 
Fixed it in the comment now. So this doesn't work as well. 
The docs and the example use it as well.

**Comment by deargle** [comment]
Yeah that would only affect hit creation anyways.

Show what urls you are trying to use to access your server, both locally
and externally. Public access definitely works for me for my stuff. Are you
certain it's not a firewall issue?  It must be, if you can access locally
but not externally (assuming you're on the same network). Have you tried
other ports?

**Comment by zahybnaya** [comment]
I have tried different ports. 
I also tried running an apache server on that port (no problem). 

I am accessing http://{hostname}:5001 
Also tried (the public, static) ip address instead of hostname to rule out DNS issues.
 Also tried via curl to rule out a browser issue.

**Comment by colinquirk** [comment]
Hi, was dealing with this issue after yesterday's crash. A hit that was working was suddenly not accessible. What worked for me was running:
`sudo pip install psiturk --upgrade`
A dependency got upgraded for me (Jinja, maybe others I don't remember) and now everything is working again.

**Comment by deargle** [comment]
fwiw I use bleeding-edge psiturk (master branch) and don't have any problem
with this. I can't think of why a psiturk ad server issue would suddenly
impact the ability of gunicorn to bind to 0.0.0.0

Are you getting any related errors in server.log?

**Comment by zahybnaya** [comment]
no errors in server.log (kept the default debug settings). 
the psiturk was installed on this server yesterday (or the day before...) so it's pretty up to date. 

not sure gunicorn does not bind to 0.0.0.0 because I CAN reach the server with the hostname (but only locally).

**Comment by deargle** [comment]
Confirm that it bound to 0.0.0.0 by running: `netstat -tulpn | grep 5001`?

**Comment by zahybnaya** [comment]
@colinquirk Thanks, I have tried to upgrade and it did update Jinja, but it didn't fix the problem. 

@deargle  I am using macos.  I think this is the netstat equivalent.  

```
[fourier:~] % lsof -i -n -P | grep TCP | grep 5002
python2.7 7190 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
python2.7 7194 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
python2.7 7195 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
python2.7 7196 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
python2.7 7197 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
python2.7 7198 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
python2.7 7199 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
python2.7 7200 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
python2.7 7201 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
python2.7 7202 maadmin2    6u  IPv4 0x4225708039bf5673      0t0  TCP 128.122.87.231:5002 (LISTEN)
```

**Comment by colinquirk** [comment]
Bummer. In case it’s useful to the people assisting, whoops y’all (which I downloaded ~1 year ago) was working for me, but my other new HIT was not. I tried taking the setup example (which was made with a newer version) and making it so that all people had to do was hit a button and they would get paid, and that would not work. But then I upgraded and that HIT and my real HIT started working. I don’t know if that will be of any use, sorry I don’t have specific version numbers.

**Comment by deargle** [comment]
@zahybnaya Let's test a bare-bones gunicorn app. Make a file called `test.py` and put this into it:

``` python
def app(environ, start_response):
    """Simplest possible application object"""
    data = 'Hello, World!\n'
    status = '200 OK'
    response_headers = [
        ('Content-type','text/plain'),
        ('Content-Length', str(len(data)))
    ]
    start_response(status, response_headers)
    return iter([data])
```
Then call it via:
    
     gunicorn -b 0.0.0.0:[any port you want] test:app

Then see if you can access that? If you can't, there's something funny about your gunicorn install. Are you using a `virtualenv`? If not, try installing psiturk into a virtualenv.

(taken from [here](http://docs.gunicorn.org/en/stable/run.html))

**Comment by zahybnaya** [comment]
I wasn't using virtualenv. 

Now, I've Installed psiturk in virtualenv. Same thing. 

can't access the gunicorn test.app example. 

```
[psiturk-env] [fourier:~/rushhour/psiturk-rushhour]%  gunicorn -b 0.0.0.0:5002 test:app
[2017-11-20 17:42:18 -0500] [7617] [INFO] Starting gunicorn 19.4.5
[2017-11-20 17:42:18 -0500] [7617] [INFO] Listening at: http://0.0.0.0:5002 (7617)
[2017-11-20 17:42:18 -0500] [7617] [INFO] Using worker: sync
[2017-11-20 17:42:18 -0500] [7620] [INFO] Booting worker with pid: 7620
 
```

Same result as outside the virtualenv.

**Comment by deargle** [comment]
But it works on localhost, right? What kind of firewall do you have that
_might_ be filtering just gunicorn traffic? Can you describe your
networking setup?

**Comment by zahybnaya** [comment]
I am working closely with our network admin. 
Ports are open to all services.

**Comment by deargle** [comment]
How about a firewall on the mac?

If you can get apache or nginx set up, and if gunicorn works locally, you
can set up a reverse proxy. See the docs for use_psiturk_ad_server or
adserver_rev_proxy or something like that.

**Comment by deargle** [comment]
Also, just because a port is open doesn't mean that the application itself
isn't blocked. Could be blocked at mac firewall level or somewhere else
(still unsure about your network topology).

Mac application firewall: https://support.apple.com/en-us/HT201642

**Comment by zahybnaya** [comment]
@deargle Yes. I think you were right. It wasn't the fw rules but the Apple application fw.
I have modified the com.apple.alf.plist file by hand and restarted the socketfilterfw
by hand.  Now it works! 
Thanks a lot.

**Comment by deargle** [comment]
Glad it works. Can you share the plist edit you made, in case others run
into this issue?

**Comment by zahybnaya** [comment]
Modify  /Library/Preferences/com.apple.alf.plist
by adding the following to the firewall section of that file.
```

                <key>Python 2.7 anaconda</key>
                <dict>
                        <key>proc</key>
                        <string>python2.7</string>
                        <key>state</key>
                        <integer>0</integer>
                </dict>
```


Then restart socketfilterfw via
```

/usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
/usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on


```
