### ISSUE TITLE
Sandbox mode hits supports multiple workers?

### ISSUE THREAD

**Issue by zahybnaya** [NYUCCL/psiTurk#289]
Is it possible that only a single hit can be performed in sandbox mode (by any worker) or multiple hits can be accessed at the same time? Am I creating the hit correctly?  How can I create multiple hits in the same "HIT group"?

I am using "hit create" to create hits in sandbox mode.  I get the two urls of "mturk url" and the "ad url".
  
This is usually what happens:
```
Ad url:
-------  
"Error: 1018
Description: The requested HIT is not registered with the psiTurk ad server.
HITId: #[u'debugH82VCB']
WorkerId: #[u'debugSR8HJW']"
```
```
Mturk url: 
----------  
"There are no HITs in this group available to you at the moment (why?) "
```

additional info:

1) I tried this several of times with different number of workers in the 'hit create'. 
2) the hit will work some times. Usually once or twice, and then it will fail. 
3) hit list shows something like this: 
        Status: Assignable
        HITid: 3LEG2HW4UFVYJ3NB0BJ8IH8CHED2FZ
        max:10/pending:0/complete:0/remain:10
        Created:2017-12-07T23:05:40Z
        Expires:2017-12-13T03:05:40Z
(not expired, plenty of hits remaining).

Thanks.

**Comment by zahybnaya** [comment]
Added `allow_repeats = true` to the hit configuration in config.txt. 
Same deal.   
Is there any way to create a hit/hit group such that  "HITs Available" on mturk show more than 1?

**Comment by deargle** [comment]
The ad url error message you show has 'debug' in it, that's not right.
That's not what hit create gives you. Not that you can use the hit create
ad url to run the study anyhow.

And I'm not sure how to make more than one available within the same HIT
group. Maybe don't run all the way to the end, so that it doesn't submit.

**Comment by zahybnaya** [comment]
@deargle  That's not clear to me. The 'debug' seems not right to me too. But that's what happens when I create the hit from psiturk. 
Did I create the hit correctly? Do I have something wrong in the configuration somewhere?

**Comment by deargle** [comment]
Sorry, I was mistaken, having `debug` in the ad url should work for displaying your ad. 

But you _cannot_ use that url to perform the experiment. You can only use it for viewing your ad. See the note below the error messages: `Note: This url cannot be used to run your full psiTurk experiment.  It is only for testing your ad.` If you try to use it to run the experiment anyway, you'll get your error message. You need to go through the MTurk URL to perform the experiment.

**Comment by zahybnaya** [comment]
Perfect! But in that case, what about the mturk link? why do I get the `"There are no HITs in this group available to you at the moment"`.  If this is because a hit can be taken only once by any worker than is `allow_repeats = true` not working?

**Comment by deargle** [comment]
It's a Mturk restriction that a worker can only perform one assignment from a HIT. You have to create multiple Hits for `allow_repeats` to be applicable. Identical HITs are grouped together on the mturk screen, only displaying one entry for each group of hits. (I think.)
