### ISSUE TITLE
Ads cannot be deleted, edited or viewed on "https://psiturk.org/dashboard/ads#"

### ISSUE THREAD

**Issue by zahybnaya** [NYUCCL/psiTurk#290]
"Actions" button does nothing. 
Tried on Chrome and Safari.

**Comment by gureckis** [comment]
👍 probably true.  the dashboard isn't a feature that has been heavily developed as many don't use it at all.

**Comment by zahybnaya** [comment]
Maybe disable the button for now?

**Comment by Speldosa** [comment]
...or just put a sentence in the description saying: "The action buttons are, for the moment, non functional" or something similar. It's quite confusing for users (and time wasting if they, like me, try to figure out why nothing happens when you push the buttons).

**Comment by deargle** [comment]
willnotfix
