### ISSUE TITLE
Displaying only dollar part of reward payment after submission

### ISSUE THREAD

**Issue by kasmith** [NYUCCL/psiTurk#293]
When I submit a HIT using the latest psiTurk version (2.2.3), the amount of the reward displayed in the confirmation message appears to display only the dollar value of the reward per hit, and not the cents (see the screenshot below -- posted reward of $2.50, displayed reward of $2). All of the other values work out as if the correct reward value was input, so I believe this is just a display issue.

![screen shot 2018-01-11 at 11 39 37 am](https://user-images.githubusercontent.com/923839/34843891-a4c2b67e-f6c4-11e7-895c-9ba473c01f20.png)

**Comment by deargle** [comment]
This is fixed on the master branch (see here: https://github.com/NYUCCL/psiTurk/blob/4f41b238ea692345783cfeba012dfa6a30558ed8/psiturk/psiturk_shell.py)
