### ISSUE TITLE
Psiturk Ad Server is down due to heavy load

### ISSUE THREAD

**Issue by fredcallaway** [NYUCCL/psiTurk#296]
https://ad.psiturk.org/

**Comment by gureckis** [comment]
yes, self-hosting ads is the solution until this is resolved:

from @deargle:
Herkou is your best bet for quickly self hosting, but there's a bit of setup required. Start reading here : https://github.com/NYUCCL/psiTurk/issues/254#issuecomment-282862588

**Comment by gureckis** [comment]
hesitantly, it is back online.  i didn't do anything but perhaps the process was put in time-out for overuse and is set free again.

**Comment by gureckis** [comment]
for reference, the error message comes from Passenger (https://github.com/phusion/passenger) which runs the web server application stack on behalf of Flask.  i’m not sure how the hosting company configures it but it can get overloaded if too many workers are viewing and completing
hits at the same time.  it might be wise to take it easy with the size of your assignments until cogsci deadline passes on Feb 1.

**Comment by deargle** [comment]
I just updated https://github.com/NYUCCL/psiTurk/issues/254#issuecomment-282862588 to be more self-contained. For those who want to use heroku, you only need to read that comment, and [this one](https://github.com/NYUCCL/psiTurk/issues/254#issuecomment-305229718) for a convenience python script (also available [here](https://github.com/NYUCCL/psiTurk/blob/908ce7bcfc8fb6b38d94dbae480449324c5d9d51/psiturk/example/set-heroku-settings.py))

**Comment by gureckis** [comment]
:+1:
