### ISSUE TITLE
Cannot log in, no contact info

### ISSUE THREAD

**Issue by patatez** [NYUCCL/psiTurk#298]
I am having problems in logging into psiturk. I am aware this is an irrelevant issue for the git page but there were no contact information on the psiturk website, and i did not want to send mails to the people within the computation and cognition lab. Where are we supposed to contact with log in related issues, or any issues with the accounts?

**Comment by gureckis** [comment]
email authors@psiturk.org with a description of the issue and your user/pass and we'll look into it.
