### ISSUE TITLE
Add participant age restriction

### ISSUE THREAD

**Issue by Speldosa** [NYUCCL/psiTurk#312]
I know that you can restrict the age of your workers when creating a HIT via the Amazon Mechanical Turk web page. However, is this possible to do when creating a HIT using psiTurk? Or would it be possible to modify/add a new criteria to the HIT afterwards somehow?

**Comment by deargle** [comment]
You cannot do it at present with psiturk, but you can modify psiturk to do
it. Look at recent-ish commits on master for Master Worker qualification
and min num approved requirements for where and how to modify the code.

**Comment by Speldosa** [comment]
So this would be the only way of doing it then?

Sure, I could take a look.

**Comment by deargle** [comment]
Only way as far as I know.

**Comment by Speldosa** [comment]
I've been digging around a bit in the `boto` API (version 2, which psiTurk is using, and version 3). There seems to be classes that deals with certain qualifications directly, such as number of HITs completed that @deargle referenced above. It's still not clear whether the [Premium Qualifications](https://blog.mturk.com/introducing-premium-qualifications-1e473456e7b0) can be accessed via the API though.

I've only seen [one discussion directly addressing this issue](https://stackoverflow.com/questions/42965801/does-boto-support-for-hit-visibility), and there it's suggested that you should create your hit via the Amazon webpage (with your custom qualifications) and then tell `boto` you want to use that specific HIT.

**Comment by Speldosa** [comment]
I've noticed that there are services like [TurkPrime](https://www.turkprime.com) (I guess [Prolific](https://www.prolific.ac) works as well) where you can specify what type of participants you want and then send them to an external URL where they'll eventually will get a code that they can use for payment. 

This would be suitable for my needs as well. You could simply rewrite `default.html` (found in the example) to invoke the lab mode (discussed in issue #95) and `thanks-mturksubmit.html` to include the payment code.

I realize that this is somewhat of a hacky solution where several things probably could backfire, but it seems like my best option for getting this thing up and running.

Ping issue #186 where it's discussed how to make psiTurk more independent from Amazon Mechanical Turk (something that I'm onboard with).

**Comment by deargle** [comment]
And `age` is really a "premium qualification"? That's dumb.

**Comment by Speldosa** [comment]
From what I can tell, neither TurkPrime nor Prolific can add any random strings to your URL (TurkPrime does it if you run experiments exclusively on Mechanical Turk, but that's effectively like running the experiment on Mechanical Turk yourself, and you don't get any extra filtering options here).

I guess Amazon wants to get some extra profit by having things like age and gender as premium qualifications, which I guess is up to them, but it's strange that you can't really access them via the API (or so it seems).

**Comment by jodeleeuw** [comment]
Prolific will add the participant and session ID to your URL if you want.

**Comment by Speldosa** [comment]
@jodeleeuw Nice! I didn't see an option regarding that when creating a test study in Prolific. Is it obfuscated somewhere?

***

Also, I just realized that you can create a HIT directly on the Amazon Mechanical Turk website (I don't know why I didn't think about this before) and use the "Survey link" option to send the participants to your psiTurk server. With this method, you can also access and use the Premium Qualifications. [It also seems](https://stackoverflow.com/questions/2916994/how-do-you-specify-the-requesters-workerid-in-a-mechanical-turk-hit/13727863#13727863) like a string with information about the participant is added to the URL.

**Comment by jodeleeuw** [comment]
Yes, it is kind of buried in the new interface. It used to be obvious. Here's the relevant doc:  http://help.prolific.ac/getting-started-launching-your-first-study/how-to-get-the-participant-id-from-a-query-string

**Comment by nicoa47** [comment]
@Speldosa Regarding your suggestion to use AMTs "Survey Link" option directly, how do you obtain the relevant psiturk link to the experiment? AFAIK you'd need to use "hit create" in the psiturk console, but wouldn't this inseparably create a link on AMT - and thus make the ad visable for ANY age range?

**Comment by deargle** [comment]
on mobile, but no, you would not use "hit create." See earlier links to discussion about "lab mode." Gist is, you enter a direct link to your experiment server for participants, on the aws mturk web interface. Your psiturk server is always accessible via the direct link, whether you create a hit from console, web, or nowhere.

**Comment by deargle** [comment]
alternative is to do something like what requesters had to do before premium qualifications existed -- give a presurvey where you survey things like age, and then create your own custom qualifications. I just added some custom block / require functionality to master, extending off of what @fredcallaway was talking about and doing in a more recent issue.

**Comment by fredcallaway** [comment]
Awesome, great work @deargle!

**Comment by nicoa47** [comment]
@deargle Thank you for the fast response! I was not aware that the other modes work as direct links.

I'm still confused how the exact link should look like. I assume it's of the shape
_{IP}:{port}/{html-site-name}?hitId={xxx}&assignmentId={yyy}&workerId={zzz}&mode=lab_
({...} are variables)?

Are all Id's in the link obligatory? If so, how to ensure participants have unique Ids in the URL via AMT?
Or, if the link stays the same, how ensure that they don't pass the link around?

**Comment by deargle** [comment]
> Or, if the link stays the same, how ensure that they don't pass the link around?
psiturk will block a worker from taking the task more than once -- that's a core feature

> Are all three ID's in the URL obligatory? If so, how to ensure participants have unique ID's in the URL via AMT?
In short, AMT generates the url based on the ad url base that we set when posting the experiment, feeding in the current hitId, assignmentId, and workerId when someone "accepts" the hit.
