### ISSUE TITLE
Live HITs suddenly missing from `hit list` 

### ISSUE THREAD

**Issue by Speldosa** [NYUCCL/psiTurk#315]
I've ran and completed a number of HITs and was about to approve pay for my workers. However, when I run the `hit list` or `worker list` command, none of them shows up anymore. I've been digging around in the manual for information regarding how long HITs will stay, when and why they dissapear, and how you can pay your workers even if you can't access them via the psiTurk interface.

**Comment by jacob-lee** [comment]
Did you run `hit dispose`?

**Comment by Speldosa** [comment]
I did not. It's just been a couple of days with inactivity from my side.

**Comment by deargle** [comment]
Best guess, you're in the wrong "mode" in ths shell.

**Comment by Speldosa** [comment]
Doh.
