### ISSUE TITLE
sockets in custom code?

### ISSUE THREAD

**Issue by bsheline** [NYUCCL/psiTurk#319]
My experiment has a web-gl object that requires websocket connections, which I have tested with [flask-socketio](http://flask-socketio.readthedocs.io/en/latest/). However, since socket-io wraps the flask app: `socketio = SocketIO(app) \n socketio.run()`; I can't figure out how to embed these modifications in custom.py, because as far as I can tell psiturk just looks for a regular flask blueprint named "custom_code" and registers it with its own internal app. 

I see how experiment.py might be modified to serve my purposes, but AFAIK a different sort of modification to the gunicorn server would be required to get it to actually run in the shell with "server on", but at this point I'm feeling out of my depth. 

Any suggestions?

**Comment by deargle** [comment]
I think you just add `socketio = SocketIO(app)` in experiment.py, and then
you should be able to use the @socketio decorator in `custom.py`. No need
to use the socketio server. Is that what you found?

**Comment by bsheline** [comment]
No, because the psiturk shell loads experiment:app. I found that you can inject WSGI middleware into a flask app by `app.wsgi_app = socketio.Middleware(sio, app.wsgi_app)` so I modified experiment.py to look for the attribute in custom.py (like it looks for custom_code) and It seems to work.

Also, I was getting an issue running the server @ https://github.com/NYUCCL/psiTurk/blob/36c1c00bdd8737e63cde007aca41b25f18305aac/psiturk/amt_services_wrapper.py#L298

So I forked an older commit.. make of that what you will.

**Comment by deargle** [comment]
What issue were you getting at L298?

**Comment by bsheline** [comment]
closed repo
pip install .
cd ExperimentFolder
psiturk

```
Sorry, unable to connect to Amazon Mechanical Turk. AWS credentials invalid.
Traceback (most recent call last):
  File "/home/osboxes/temp/temp/bin/psiturk", line 11, in <module>
    sys.exit(process())
  File "/home/osboxes/temp/temp/local/lib/python2.7/site-packages/psiturk/command_line.py", line 15, in process
    launch_shell()
  File "/home/osboxes/temp/temp/local/lib/python2.7/site-packages/psiturk/command_line.py", line 115, in launch_shell
    ps.run(cabinmode=args.cabinmode)
  File "/home/osboxes/temp/temp/local/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 1218, in run
    quiet=quiet)
  File "/home/osboxes/temp/temp/local/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 747, in __init__
    self.update_hit_tally()
  File "/home/osboxes/temp/temp/local/lib/python2.7/site-packages/psiturk/psiturk_shell.py", line 852, in update_hit_tally
    num_hits = self.amt_services_wrapper.tally_hits()
  File "/home/osboxes/temp/temp/local/lib/python2.7/site-packages/psiturk/amt_services_wrapper.py", line 282, in tally_hits
    hits = self.get_active_hits(all_studies=False)
  File "/home/osboxes/temp/temp/local/lib/python2.7/site-packages/psiturk/amt_services_wrapper.py", line 302, in get_active_hits
    hits = self._get_hits(all_studies)
  File "/home/osboxes/temp/temp/local/lib/python2.7/site-packages/psiturk/amt_services_wrapper.py", line 298, in _get_hits
    amt_hits = [hit for hit in amt_hits if hit.options['hitid'] in my_hitids]
TypeError: 'bool' object is not iterable

```

**Comment by deargle** [comment]
Thank you, I can fix that.

**Comment by deargle** [comment]
Fixed, although it's possible that other things will also be broken until you enter valid amt credentials into `.psiturkconfig`

**Comment by deargle** [comment]
Also, I was just playing around with this. You can use socketio in custom routes by patching `experiment.py` thusly:

```
diff --git a/psiturk/experiment.py b/psiturk/experiment.py
index 4a3b4d8..59a61c1 100644
--- a/psiturk/experiment.py
+++ b/psiturk/experiment.py
@@ -67,6 +67,9 @@ app.config.update(SEND_FILE_MAX_AGE_DEFAULT=10)
 app.secret_key = CONFIG.get('Server Parameters', 'secret_key')
 app.logger.info("Secret key: " + app.secret_key)

+from flask_socketio import SocketIO
+socketio = SocketIO()
+socketio.init_app(app)
```

Then you can do `from psiturk.experiment import socketio` in `custom.py` in order to be able to use the `@socketio` decorator.
