### ISSUE TITLE
Awkward to use '--all-studies' for brand new HITs

### ISSUE THREAD

**Issue by ariekahn** [NYUCCL/psiTurk#328]
Spent a while trying to figure out why some new sandbox HITs I was creating weren't showing up.

It looks like HITs only show up if there's a matching participant in the database, which seems like a good idea overall, but means I have to use '--all-studies' to see HITs I just created, if no one's started on them yet. Not sure if that's intended, or what a good alternative would be?

**Comment by deargle** [comment]
Hit `title` is available. I'll change it to also return hits that have titles that match the current title in config.txt.

**Comment by deargle** [comment]
Of course, the more pure fix would be to maintain a separate table with HITs for the current study, which might be easy enough also. But adds complexity.

**Comment by ariekahn** [comment]
I'd see something like the ad group as being ideal for this, but unfortunately doesn't look like that would be easily available without some cross-referencing.

**Comment by deargle** [comment]
Just looked at the aws docs. We could set a 'RequesterAnnotation' on each created hit. Only question would be, what to set it to. If we create a new config entry like 'study id' for the requesterannotation, and then a psiturk user creates a hit, then changes the study name, they may be surprised if 'hit list' does not show their old hits. Or maybe they'd get it easily enough. Could merge that set of hits with the set of hits that have a hitid that matches an entry in the psiturk db.

Or what else might be used to uniquely identify a study for a particular requester? Perhaps the project folder name?

https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI-legacy/ApiReference_HITDataStructureArticle.html

**Comment by deargle** [comment]
And yeah `ad_group` is only currently used if someone is using the psiturk ad server.

**Comment by deargle** [comment]
My wip https://github.com/NYUCCL/psiTurk/tree/test-suite branch fixes this by tracking new hits in a new table.

**Comment by deargle** [comment]
closed by 2.3.2
