### ISSUE TITLE
Require Master Workers

### ISSUE THREAD

**Issue by bisraelsen** [NYUCCL/psiTurk#330]
Hi,

I am trying to create a hit that requires master workers using `require_master_workers = true` doesn't seem to do anything when I'm using the sandbox mode. I can see hits that others have created that require master workers and it shows a `qualify` button by their hits, by mine it shows the typical `Accept and Work` button. Am I doing something wrong?

Also, if instead I use the `approve_requirement` and `number_hits_approved` parameters, I can see the effects when changing `approve_requirement`, but I am unsure if the `number_hits_approved` value works.  The hit still shows in the sandbox even though I think my sandbox worker doesn't have thousands of approved hits.

**Comment by deargle** [comment]
You have to be using the github master version of psiturk -- not the one
from pip

**Comment by bisraelsen** [comment]
Thanks!
