### ISSUE TITLE
Pass custom error codes

### ISSUE THREAD

**Issue by bisraelsen** [NYUCCL/psiTurk#332]
Hi,

I haven't been able to find any other issues related to this.

I require participants to pass a quiz before they are able to proceed to be paid. Right now if they fail the quiz I use the `completeHIT()` method to terminate the experiment. However, if this happens then I have to reject the worker in order to not pay them for the HIT. I have read online that it is better to allow the worker to return the HIT instead of being rejected in a case like this.

So, I'm wondering if instead of using `completeHIT()` I can pass an error that brings up the error screen with a custom message like "you didn't pass the quiz, please return this HIT", and then not closing the HIT.

I would also be open to some other approach.

**Comment by deargle** [comment]
Calling completeHit in psiturk is quite basic. Redirects them to /complete
route within psiturk framework, which sets the psiturk status to 3
(complete). That page then redirects to another page that has a big fat
"submit" button that, when pressed, uses ajax to flag the worker status as
submitted (4), then tries to submit to mturk to officially flag as
complete. If you want to do something else, just create an arbitrary route
in custom.py with its own template and whatever javascript you want and use
javascript to redirect to that route. You can look in experiment.py to see
how it is handled for the built-in routes.

**Comment by jacob-lee** [comment]
If failing quiz, I just change the div content of the html with a message
telling them that they are ineligible and why, and asking them to return
the HIT. I do not provide any means of proceeding, or submitting, so they
just return the HIT. Works out fine.

**Comment by bisraelsen** [comment]
@deargle and @jacob-lee thanks for the feedback. I've been trying to write a custom route, but I'm not sure how to evoke it from javascript. My code in `custom.py` is basically:

```
#----------------------------------------------
# Error for quiz failure
#----------------------------------------------
@custom_code.route('/quiz_fail')
def quiz_fail():
	current_app.logger.info("Reached /quizFail")  # Print message to server.log for debugging
    	try:
	    	return render_template('quizFail.html')
    	except TemplateNotFound:
	    abort(404)
```

I'm not sure what to put in javascript to access it though.

**Comment by deargle** [comment]
Url redirect to that route via javascript, but jacob-lee 's idea is better.
