### ISSUE TITLE
Unused template parameter server_location in ad.html

### ISSUE THREAD

**Issue by ariekahn** [NYUCCL/psiTurk#334]
I can't tell if `server_location` is (or ever has been) used.

The example template `ad.html`, for the button to launch an experiment, links to `{{ server_location }}/consent?hitId={{ hitid }}&assignmentId={{ assignmentid }}&workerId={{ workerid }}`

Was playing around with displaying an alternative URL, but I don't think that parameter is actually getting passed in at all.
The link I'm seeing on MTurk ends up being `/consent?hitId=x&assignmentId=x&workerId=x`, and I assume the base URL is getting added automatically from the embedded iframe on Amazon's site. I can't find any reference to it outside of the template.

See:
https://github.com/NYUCCL/psiTurk/blob/9806225fa3a5dbb2c64c86bc42067a77462f9d72/psiturk/example/templates/ad.html#L59
https://github.com/NYUCCL/psiTurk/blob/9806225fa3a5dbb2c64c86bc42067a77462f9d72/psiturk/example/templates/ad.html#L113 https://github.com/NYUCCL/psiTurk/blob/9806225fa3a5dbb2c64c86bc42067a77462f9d72/psiturk/experiment.py#L332-L340

**Comment by deargle** [comment]
IIRC it gets filled in if you are using the psiturk ad server. The ad server somewhat myopically sets the server_location to be the public ip resolvable to the address of the server from where the ad was created, around here:

https://github.com/NYUCCL/psiTurk/blob/9806225fa3a5dbb2c64c86bc42067a77462f9d72/psiturk/amt_services_wrapper.py#L493

`server` in that config gets used as the `server_location` on the psiturk ad server render function.

But you can override that if you use the `adserver_revproxy_host` config (maybe only if using psiturk master):

https://github.com/NYUCCL/psiTurk/blob/9806225fa3a5dbb2c64c86bc42067a77462f9d72/psiturk/amt_services_wrapper.py#L477

**Comment by gureckis** [comment]
yes the ad.html uploaded to the ad server and this template variable is provided by the server itself to allow
people to find your local psiturk instance.  so you might not see reference to that variable in the psiturk codebase
but that is because this is one aspect handled on the server side.

**Comment by ariekahn** [comment]
Ok, thanks for the clarification!

Probably should have mentioned I was testing this out though Heroku and serving the ad there, which was giving me the relative URL. Just verified that `server_location` gets filled in when I switch back to the psiturk ad server.

Might be worth noting in the template or documentation.

**Comment by deargle** [comment]
If you are using heroku, you can host your own ad right on the same heroku instance -- they provide free https. See `use_psiturk_ad_server = false` in docs or something like that.

**Comment by ariekahn** [comment]
Hosting the ad on the heroku instance seems to work fine.

My point was just that when hosting on the heroku instance, it doesn't fill in  `server_location`, which isn't strictly an issue for hosting the ad, but was a little confusing when working with the ad template.

**Comment by deargle** [comment]
Ah, true, yes that would be confusing
