### ISSUE TITLE
server_config is replaced with an incorrect location.

### ISSUE THREAD

**Issue by jpalat** [NYUCCL/psiTurk#337]
httpbin.org now returns origin in the following format:
{
  "origin": "xxx.xxx.xx.xx, xxx.xxx.xx.xx"
}
As a result the server_config is replaced as  "xxx.xxx.xx.xx, xxx.xxx.xx.xx" which breaks ad.html and points forward.

**Comment by deargle** [comment]
wat

**Comment by jpalat** [comment]
Added more detail in the first comment.

**Comment by deargle** [comment]
Open to submitting a PR?

**Comment by gureckis** [comment]
!!

**Comment by jpalat** [comment]
PR Submitted (#338)

**Comment by deargle** [comment]
Merged #338 thanks x100

**Comment by deargle** [comment]
@gureckis we should probably push again to pip, although I was in the middle of refactoring back a few months ago directly to master because I am crazy. I think it's stable though...

**Comment by deargle** [comment]
issue was raised here https://github.com/postmanlabs/httpbin/issues/535
