### ISSUE TITLE
'mode' lacks a safety check or reasonable default in the /ad;/pub route

### ISSUE THREAD

**Issue by Wildcarde** [NYUCCL/psiTurk#341]
I'm currently working on trying to add turkprime support via a custom route in psiturk. I'm taking this approach primarily because I needed to be able to add the 'mode' flag since there's no safety check for it here: https://github.com/NYUCCL/psiTurk/blob/master/psiturk/experiment.py#L275

However it's falling a bit short due to the way data is accessed in the advertisement function, specifically using `request.args` since flask doesn't seem to supply any sort of way to append to that as part of developing a url and providing a redirect.  My current working attempt is included below:

```
@custom_code.route('/turkprime')
def turkprime():
	@after_this_request
	def add_mode(response):
                #extract arguements
		data=request.args.to_dict(flat=False)
		data['mode']='live'
                #retrieve url (unfortunately doesn't return a string that can be manipulated
		url = url_for('advertisement')
                #create new response dataset with mode appended correctly
		response.set_data(json.dumps(data))
                #redirect to correct url
		return redirect(url)
```

I should note, this doesn't work, but I'm pretty sure it would if instead of `requests.args` it used `requests.data` but have not checked this yet (I'm trying to make a custom function that avoids touching the psiturk core code so we aren't running an aberrant fork of the base code).  My next approach I think will be to desconstruct the full URL from the requests info and build out a new one with the data supplied appended to it and given directly to the redirect.

The end goal is to get the test url from TurkPrime: `http://localhost:22362/turkprime?workerId=ABCD1435&hitID=35hgfsbdu&assignmentId=vbwjebwufg`

To end up at: `http://localhost:22362/ad?workerId=ABCD1435&hitID=35hgfsbdu&assignmentId=vbwjebwufg&mode=live`

**Comment by deargle** [comment]
You can [build urls](http://flask.pocoo.org/docs/1.0/quickstart/#url-building) with `url_for`, instead of trying to re-pass the data object from the original request

**Comment by Wildcarde** [comment]
I've found a (seemingly) working solution:
```
@custom_code.route('/turkprime2')
def turkprime2():
	newrstring=request.query_string+'&mode=live'
	url=request.url_root+'/ad?'+newrstring
	print("url: ",url)
	return redirect(url)
```

It's a bit bruteforce, but seems to get me from: `http://localhost:22362/turkprime2?workerId=ABCD1435&hitId=35hgfsbdu&assignmentId=vbwjebwufg` to my desired location.

Or at least pushes the issue further down the line.

**Comment by deargle** [comment]
You can configure your code to not use the psiturk ad server, then you should be good.
