### ISSUE TITLE
"psiturk-setup-example: command not found" when attempting to setup first experiment.

### ISSUE THREAD

**Issue by cmahlen** [NYUCCL/psiTurk#342]
Hello everyone,

I just recently installed psiturk and I am having trouble running the initial stroop task. I've followed along the two following guides (in the order they are listed), and have run into errors in each case:

http://psiturk.org/quick_start/
https://github.com/NYUCCL/psiTurk/wiki/Quickstart

In both tutorials, whenever I reach the step that tells me to enter the psiturk-setup-example command into the terminal, the output just says that this command is not found. I have looked around at other forums and haven't found anyone encountering any similar problems. I am not really sure what to do at this point, so any help would be greatly appreciated.

**Comment by jacob-lee** [comment]
You need to make sure psiturk is on your path. Check your path variable.

**Comment by cmahlen** [comment]
So I checked my paths using the
printf "%s\n" $PATH
command and the output was this (in addition to some other things):
/Library/Frameworks/Python.framework/Versions/2.7/bin
Then I put my psiturk folder into that bin folder and tried running the psiturk-setup-example command again, and nothing happened. Do I need to change the path or use a different one?

**Comment by deargle** [comment]
Your psiturk install perhaps was not successful.

**Comment by cmahlen** [comment]
I think you were right. I uninstalled it using pip (I figured something like this was the problem a few days ago and foolishly just deleted the psiturk file by moving it to trash, which failed) and then reinstalled it, and it worked. Thanks!
