### ISSUE TITLE
heroku deployment crashes with psycopg 2.7.1.

### ISSUE THREAD

**Issue by fohria** [NYUCCL/psiTurk#343]
This is similar to #299 , but now apparently 2.7.1. is not good enough either. Deploying to heroku yields following error in heroku app log:

```
2019-03-19T21:13:53.655151+00:00 app[web.1]: ImportError: /app/.heroku/python/lib/python2.7/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
2019-03-19T21:13:53.702751+00:00 app[web.1]: Caught ^C, experiment server has shut down.
2019-03-19T21:13:53.702754+00:00 app[web.1]: Press `enter` to continue.
2019-03-19T21:13:53.815149+00:00 heroku[web.1]: State changed from up to crashed
```

Changing requirements.txt to using 2.7.7 fixes the issue. I'll make a pull request shortly for this change

**Comment by deargle** [comment]
I wonder if there's a way for our project to auto require whatever is the current heroku min-supported version

**Comment by fohria** [comment]
I've no idea. In this is, it might be related to psycopg2 using C libraries? [https://devcenter.heroku.com/articles/python-c-deps](url)

On that note though, I noticed when troubleshooting that if version is not specified in requirements.txt, heroku will use whatever version is installed and not automatically check for a later one. So for example, when 2.7.1. was installed from a previous build and I changed requirements file to no version number at all, it just used the 2.7.1.

Though maybe that's a python thing and not specific to heroku?

**Comment by deargle** [comment]
I think that's a pip thing -- pip is used to install from requirements.txt

I'll merge the PR as soon as you open it

**Comment by fohria** [comment]
Oh, PR was already created, I clicked "merge" now, I hope this wasn't in error. (my first time pull requesting on github)

**Comment by deargle** [comment]
Hmm, no, it looks like you merged your branch into your repo's own master branch. Try following this: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by deargle** [comment]
I figured out how to create and merge a PR from your fork. Thanks!

**Comment by fohria** [comment]
Ohh, haha, I didn't realize I created the pull request on my own fork. Sorry about that, thanks for making the effort to correct my mistake!
