### ISSUE TITLE
[Fixed]: AWS Requester API no longer supported

### ISSUE THREAD

**Issue by rjhubbard88** [NYUCCL/psiTurk#348]
Hi there,
I've installed Psiturk 2.2.4 on my Linux Mint machine and attempted to run it (I have an AWS account and credentials, as well as Psiturk, and have changed the global configuration file).  I get the following error:

> This Requester API is no longer supported. Please use the latest API using the official AWS SDK. https://aws.amazon.com/getting-started/tools-sdks
WARNING *****************************
Sorry, AWS Credentials invalid.
You will only be able to test experiments locally until you enter
valid credentials in the AWS Access section of ~/.psiturkconfig

I see a blog post from Mturk about this issue: https://blog.mturk.com/older-versions-of-the-mturk-requester-api-to-be-deprecated-beginning-june-1st-2019-9fcc9791fa18

It's not quite June 1st, but maybe they rolled this out already and Psiturk won't work without Boto3? Unless of course I'm just making a mistake somewhere.

Thanks in advance.

**Comment by deargle** [comment]
https://groups.google.com/d/msg/psiturk/x8tcm0I2EPk/psqGsMzuDQAJ

**Comment by rjhubbard88** [comment]
Perfect, I installed from pip so that explains it.  Thanks Dave.

**Comment by deargle** [comment]
nw. I'm going to reopen this until I update pip.

**Comment by deargle** [comment]
I'm still leaving this open since the api retirement date is tomorrow (June 1st), but v2.3.0 is published on pip now, and is compatible with the new api.

**Comment by yang-yangfeng** [comment]
Seems like the AMI does not have these changes?

**Comment by deargle** [comment]
I don't support the AMI.
