### ISSUE TITLE
How to retrieve/cancel the extended assignments

### ISSUE THREAD

**Issue by ikol172q** [NYUCCL/psiTurk#353]
Hello everyone, 

Our experiment has been done and I extended the hit by increasing the number/time of *--assignments* and the *--expiration*. Unfortunately, I don't have enough money for those extended assignments which results in the failure message as follows,
```
Failed to extend HIT ****. Please check the ID and try again.
```
And there are too many *remain* left as follows, 
```
max:1027/pending:0/complete:485/remain:542
```

I want to clear all remain because of the funding issue...

Is it possible to cancel/retrieve my previous extend action? Or is there a way to prevent those people who have already done this experiment if we restart a new hit?

Thank you!

**Comment by deargle** [comment]
`hit expire`

**Comment by ikol172q** [comment]
Thanks! I've tried `hit expire`, but the number of `remain` is still the same.

**Comment by deargle** [comment]
If the hit is in state "reviewable" and not "assignable", then no one else
can start it. What is the status of the hit as shown by `hit list`?

**Comment by ikol172q** [comment]
The current status of this hit is "Reviewable". Do you mean that I should make is assignable, then `hit expire hit_id`? That's what I did when I saw the failure message. But the `remain` number is still the same.

**Comment by deargle** [comment]
No, I think you're all set. No one else can take it now, even though a lot
"remain."

**Comment by deargle** [comment]
If you're asking about getting the money refunded, i'm not sure exactly how
that works or when it happens. You probably will have the prepaid money
sitting in a balance account.

**Comment by ikol172q** [comment]
I see. Actually, I want to use  But I want to keep using this hit to avoid repeated workers with fewer assignments (current number of remain is 542, I want to reduce it less than 150). Is there a way to reduce the number of `remain`?

**Comment by deargle** [comment]
Psiturk blocks repeat workers across hits. It checks against your local db
to see if a workerid has already done one of your experiments.

**Comment by ikol172q** [comment]
That's awesome! Can I keep the current database and create a new hit based on this experiment so that the existed worker_id will not do it again?

**Comment by deargle** [comment]
Yes. New to psiturk I take it? ;-)

**Comment by ikol172q** [comment]
Yeah, I'm new to this XD... Thank you so much! Let me try it and come back for the feedback!

**Comment by ikol172q** [comment]
BTW, what if I reset the database...Is there a hope to still avoid the worker_ids who have done the experiment?

**Comment by Portll** [comment]
Once you've expired the HIT you can use assignQualification or the MTurk
admin panel to add a new qualification and give it to everyone who did the
experiment.

You can then exclude anyone matching that qualification from your new
batches.

You may want to asssign qualification using the API into the end of your
HIT so there is a hard barrier preventing retakes

**Comment by deargle** [comment]
Or just export the worker ids from your db before wiping it, and import
them into your new database.

**Comment by ikol172q** [comment]
Thank you so much!! @Portll @deargle ! Since I've reset the database before...I may need to use the Mturk admin panel to control or import them again...Thank you!!!
