### ISSUE TITLE
HITs always post to Sandbox

### ISSUE THREAD

**Issue by rjhubbard88** [NYUCCL/psiTurk#357]
I'm having an issue where using `hit create` creates a HIT on the MTurk sandbox, even if my mode is set to Live, server is on, etc.  I downloaded Psiturk from GitHub less than a month ago, so I don't think it's a version issue.  I've posted my config file below - am I just making a mistake somewhere?

>[HIT Configuration]
title = Test Your Memory
description = Test your memory for a series of stimuli.
amt_keywords = Memory, Psychology
lifetime = 24
us_only = true
approve_requirement = 95
number_hits_approved = 0
require_master_workers = false
contact_email_on_error = rjhubba2@illinois.edu
ad_group = Memory
psiturk_keywords = memory
organization_name = University of Illinois, Urbana-Champaign
browser_exclude_rule = MSIE, mobile, tablet
allow_repeats = false

>[Database Parameters]
database_url = postgres://sfvwicbofuxcip:37cf36cc1edc0f8ec06265df8436af783a6ea4200c67e844078437708b9546d8@ec2-54-243-197-120.compute-1.amazonaws.com:5432/d18h3e34coh101
table_name = turkdemo

>[Server Parameters]
host = 0.0.0.0
port = 22362
cutoff_time = 30
logfile = server.log
loglevel = 2
debug = true
login_username = examplename
login_pw = examplepassword
threads = 1
secret_key = 'this is my secret key which is hard to guess, i should change this'
#certfile = <path_to.crt> 
#keyfile = <path_to.key>
#adserver_revproxy_host = glacial-shore-83079.herokuapp.com
#adserver_revproxy_port = 80
server_timeout = 30

>[Task Parameters]
experiment_code_version = 1.0
num_conds = 1
num_counters = 1

>[Shell Parameters]
launch_in_sandbox_mode = true
#bonus_message = "Thanks for participating!"

>use_psiturk_ad_server = false
ad_location = https://glacial-shore-83079.herokuapp.com/pub

**Comment by deargle** [comment]
Update psiturk. There was a bug about a month ago that has since been fixed.

**Comment by deargle** [comment]
You can install from pip now to get v2.3.2 which should work.

**Comment by rjhubbard88** [comment]
Ah, I must've just missed this update. I'll update now, thanks much.

**Comment by rjhubbard88** [comment]
Well, after updating to 2.3.2 the HIT no longer always posts to Sandbox... but now unfortunately when in Live mode simply posts nothing at all. Psiturk thinks there's a HIT posted (I can see it with `hit list` ), but there's nothing visible on MTurk.

**Comment by deargle** [comment]
That's not necessarily incorrect -- does hit list report that there are no
more assignments available for that hit? Hits can be gobbled up into a
worker's queue using worker automated tools before the hit gets a chance to
appear on the website.

**Comment by rjhubbard88** [comment]
Ah, I think you might be right - hit list reads:

> Status: Unassignable 
	HITid: 37Y5RYYI0RSQF8JZNUEG6EW7SBUSXR             
	max:20/pending:20/complete:0/remain:0

**Comment by deargle** [comment]
Sneaky mturkers at it again with their wiles

**Comment by rjhubbard88** [comment]
One more question - I now have less pending, but also no complete or remaining, and the HIT is still unassignable.  It looks like this:
>Status: Unassignable 
	HITid: 37Y5RYYI0RSQF8JZNUEG6EW7SBUSXR             
	max:20/pending:15/complete:0/remain:0 

What does this mean?

**Comment by deargle** [comment]
e.g., If the HIT lifetime is 1hr, but your task takes only 15 minutes to
complete, a worker may "grab" it with their tools, and not get around to
actually working on it until close to the expiry time. While they have it
"checked out", it will be in status pending. An assignment also goes into
"pending" status when someone is merely viewing the ad, before they have
decided whether they will accept it.

And, only HITs that you have "approved" or "rejected" will move to
"complete" status, per the AWS mturk api. See
https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_HITDataStructureArticle.html
,
NumberOfAssignments[Pending|Available|Completed|" Psiturk renames
"Available" to "remain". Point is that submitted hits that you haven't done
anything with are not included in any count returned by mturk api. So you
should have 5 workers who have submitted the task, and 15 who are holding
onto it, with no additional assignments available for a new worker to grab,
for that hit.

**Comment by rjhubbard88** [comment]
Gotcha. Thanks much for the explanation!
