### ISSUE TITLE
create_hit MissingArgumentsError is raised unexpectedly

### ISSUE THREAD

**Issue by ttomita** [NYUCCL/psiTurk#358]
I recently migrated my experiment from my own EC2 instance to Heroku (it worked fine previously). The experiment accessed via the debug link provided by `heroku domains` works just fine. However, when I try `hit create 1 0.00 1` in sandbox or live mode from within the experiment directory on my local machine, I get this error:

```
[psiTurk server:off mode:sdbx #HITs:0]$ hit create 1 0.00 1
*****************************
    Max workers: 1
    Reward: $0.00
    Duration: 1.0 hours
    Fee: $0.00
    ________________________
    Total: $0.00
Create sandbox HIT [y/n]? y
Error during hit creation.
Response(Operation: create_hit | Status: error | Exception: MissingArgumentsError: )
```

I have traced this back to `amt_services_wrapper.create_hit()`, which obviously throws the exception above if `num_workers`, `reward`, or `duration` are empty. But why are they empty?

I am running psiTurk version 2.3.2. Here is the relevant part of my config.txt file:
```
[Server Parameters]
host = 0.0.0.0
port = 23432
cutoff_time = 60
logfile = server.log
loglevel = 2
debug = true
login_username = examplename
login_pw = examplepassword
threads = 1
secret_key = 'this is my secret key which is hard to guess, i should change this'
#certfile = <path_to.crt>
#keyfile = <path_to.key>
#adserver_revproxy_host = www.location.of.your.revproxy.sans.protocol.com
#adserver_revproxy_port = 80 # defaults to 80

[Task Parameters]
experiment_code_version = 1.0
num_conds = 3
num_counters = 1

[Shell Parameters]
launch_in_sandbox_mode = true

use_psiturk_ad_server = false
ad_location = https://gentle-bayou-55010.herokuapp.com
```

Since I just moved to Heroku, it's possible I am doing something wrong. However, I can't seem to find an obvious solution.

**Comment by deargle** [comment]
0.00 reward counts as False in python. Bump it to 0.01.
