### ISSUE TITLE
potential datastring encoding issue

### ISSUE THREAD

**Issue by deargle** [NYUCCL/psiTurk#366]
> I'm looking at the database in postico, and the datastring doesn't have the data that i wrote with psiTurk.recordTrialData() anywhere in it. Is this an ok way to look at it?

2019.7.27
I have a similar problem here. I used the stroop example. All procedure in sandbox went right but finally there was no data in the heroku database.( If I run download_datafiles, there would be "('No trial data found in record:', Subject(uniqueid|A3I6Y8407JIPA1:354P56DE9L689F2BRQ3YPQSRHSSS7B, condition|0, status|4, codeversion|1.0)) -- subject id ✔ data ✘.

2019.7.29
After exporting my "heroku psql", I found the data seemed to be there (it increased with the completed hit sizes) but unreadable (garbled). Even when I just built the heroku ("git push heroku master" for the first time), there had been some unreadable things at the end of the database. I think it is an encoding problem, which might already happen before the data collection. Any suggestion could be really helpful. Thanks!

_Originally posted by @tianweigong in https://github.com/NYUCCL/psiTurk/issues/254#issuecomment-515651572_

**Comment by deargle** [comment]
@tianweigong @arbardon what version psiturk are you using?

**Comment by abardon** [comment]
I'm using 2.3.2

**Comment by deargle** [comment]
What I have so far is that it's ascii-encoded:

https://github.com/NYUCCL/psiTurk/blob/a702d0e4afc93c73718347c7fd6f329eab9b3f7c/psiturk/experiment.py#L620-L625

ascii is specified by `\x` followed by two hex characters which represents one character. 

e.g., `\x7b22636f` translates to* `{"co` -- the beginning of `{"condition":`. I'm not yet sure why it suddenly started looking like this in the db.

* Actually, `\x7b\x22\x63\x6f` does, but I suspect something implementation-specific is going on that allows for only one preceeding `\x`.

**Comment by deargle** [comment]
Replacing line 621 with `user.datastring = json.dumps(request.json)` seems to work for newly-saved data, but I'm concerned because (1) I don't know why that wasn't done in the first place (this is inherited code), and (2) see number 1.

I'm seeing if there's an easy way to recover previously-garbled data.

**Comment by deargle** [comment]
Note to self, https://github.com/NYUCCL/psiTurk/blob/a702d0e4afc93c73718347c7fd6f329eab9b3f7c/tests/test_psiturk.py#L120-L134 doesn't catch this probelm because https://github.com/NYUCCL/psiTurk/blob/a702d0e4afc93c73718347c7fd6f329eab9b3f7c/psiturk/experiment.py#L626-L635 catches decoding errors and always returns success (why?!)

**Comment by deargle** [comment]
I just fixed this on master, but master is python-3 only. I'm going to see about backporting.

**Comment by deargle** [comment]
If you update to psiturk 2.3.3, the datastring thing should be resolved.
