### ISSUE TITLE
Ad not appearing during local testing

### ISSUE THREAD

**Issue by avrvaidya** [NYUCCL/psiTurk#369]
Hello,

I'm just starting to use Psiturk and have been working on programming and debugging my experiment locally on my own machine. However, whenever I go into debug mode, my experiment ad flashes on screen for a split second and disappears. I can recreate this by refreshing the browser window rapidly, but the ad never sticks around... When I try putting my HIT on the sandbox, the ad is just a blank page... Any ideas about what I might be doing wrong?

**Comment by deargle** [comment]
Ad blocker and an old template

**Comment by avrvaidya** [comment]
Turning off ad blocker solved it! Thanks so much! 
As a follow up: Is there a more contemporary template that is ad blocker resistant that I could be using?

**Comment by deargle** [comment]
The one provided by the setup example command worked as of a few days ago,
does it no longer work?
