### ISSUE TITLE
"AWS credentials invalid" but they shouldn't be?

### ISSUE THREAD

**Issue by hstojic** [NYUCCL/psiTurk#370]
Hello,

Since updating from version 2.2.3 to 2.3.3 I suddenly get invalid credentials message:

NoMturkConnectionError: Sorry, unable to connect to Amazon Mechanical Turk. AWS credentials invalid.
You can still use the psiturk server by running non-AWS commands such as:
- `psiturk server <subcommand>`
- `psiturk server start`
- `psiturk server stop`
- `psiturk debug -p`

I checked my AWS account, all seems in order there, and I logged into my Mturk requester accounts (regular and sandbox), again nothing out of ordinary, I have some funds etc. What can I do to troubleshoot this?

Best,
Hrvoje

**Comment by deargle** [comment]
This message suggests that your creds in .psiturkconfig for aws are not
valid. Unit tests test that this works as expected. Check your creds there
-- different than your gui login creds.

**Comment by hstojic** [comment]
Hello. Yes, that was the first thing I did. I created a new set of AWS credentials as well, but these didn't work either. Is there any other way to test whether its something wrong on the AWS side? 
Perhaps AWS CLI?

**Comment by deargle** [comment]
You could try a direct mturk call with boto3. Shouldn't be more than a few
lines of code to test.

**Comment by hstojic** [comment]
OK, I tested the credentials with boto3 and everything works, I can connect to various services, start servers etc. Then I guess it has to be something in the rest of the psiturk code?

**Comment by deargle** [comment]
You tested mturk services specifically with those creds? You did not explicitly say that you tested an mturk call. Try this example code comes from https://requester.mturk.com/developer/sandbox

```
import boto3
region_name = 'us-east-1'
aws_access_key_id = 'YOUR_ACCESS_ID'
aws_secret_access_key = 'YOUR_SECRET_KEY'
endpoint_url = 'https://mturk-requester-sandbox.us-east-1.amazonaws.com'

# Uncomment this line to use in production
# endpoint_url = 'https://mturk-requester.us-east-1.amazonaws.com'

client = boto3.client(
  'mturk',
  endpoint_url=endpoint_url,
  region_name=region_name,
  aws_access_key_id=aws_access_key_id,
  aws_secret_access_key=aws_secret_access_key,
)

# This will return $10,000.00 in the MTurk Developer Sandbox
print(client.get_account_balance()['AvailableBalance'])
```

What we're looking at in psiturk is this block of code: https://github.com/NYUCCL/psiTurk/blob/4394a53133be310c147a84f8a17e91d6c7e640c1/psiturk/amt_services.py#L97-L104

Probably there is something wrong with the `.mtc` client being created around here: https://github.com/NYUCCL/psiTurk/blob/4394a53133be310c147a84f8a17e91d6c7e640c1/psiturk/amt_services.py#L224-L240

Or, the https://github.com/NYUCCL/psiTurk/blob/4394a53133be310c147a84f8a17e91d6c7e640c1/psiturk/amt_services.py#L242-L251 is failing when it tries to get your account balance. Try running the mturk-provided block of code above to see what's being returned, maybe.

**Comment by hstojic** [comment]
You are right, I didn't test an mturk call. 

I tested the first snippet now, to get the balance: while it worked for regular mturk it didn't for the sandbox version. I logged in to the sandbox to check again if something is not set up, and then in the developer tab found it wasn't linked to my AWS account. After linking it to AWS the call to the sandbox endpoint works now and I can use my account again.

Probably previous psiturk versions did not raise this error if call to the regular mturk passed, regardless of the sandbox one. I never actually used the sandbox, but I did notice that I would get an error when trying to show the balance in the sandbox mode.

Perhaps its worth adding a line about this in the documentation at https://psiturk.readthedocs.io/en/latest/amt_setup.html#creating-an-amt-requester-account? I'll send a PR

Thanks a lot for the help!

**Comment by tkbala** [comment]
> You are right, I didn't test an mturk call.
> 
> I tested the first snippet now, to get the balance: while it worked for regular mturk it didn't for the sandbox version. I logged in to the sandbox to check again if something is not set up, and then in the developer tab found it wasn't linked to my AWS account. After linking it to AWS the call to the sandbox endpoint works now and I can use my account again.
> 
> Probably previous psiturk versions did not raise this error if call to the regular mturk passed, regardless of the sandbox one. I never actually used the sandbox, but I did notice that I would get an error when trying to show the balance in the sandbox mode.
> 
> Perhaps its worth adding a line about this in the documentation at https://psiturk.readthedocs.io/en/latest/amt_setup.html#creating-an-amt-requester-account? I'll send a PR
> 
> Thanks a lot for the help!

Linking the AWS account fixed the issue for me!
