### ISSUE TITLE
Bug in Custom.py generated by psiturk-setup-example?

### ISSUE THREAD

**Issue by Speldosa** [NYUCCL/psiTurk#374]
In the file Custom.py that you get in the sample experiment when you run psiturk-setup-example, on line 9, there's a line that reads

`from psiturk.experiment_errors import ExperimentError, InvalidUsageError`

In previous versions of psiturk, this line was 

`from psiturk.experiment_errors import ExperimentError, InvalidUsage`

When using this updated Custom.py on my Heroku server, I got the following error

`2019-08-13T12:07:14.153437+00:00 app[web.1]: ImportError: cannot import name 'InvalidUsageError' from 'psiturk.experiment_errors' (/app/.heroku/python/lib/python3.7/site-packages/psiturk/experiment_errors.py)`

which in turn breaks my whole experiment.

However, this error goes away when I change the line back to the original version.

I have no idea what's happening here, but it seems like a bug to me.

I'm running the latest psiturk version from the master branch locally.

**Comment by Speldosa** [comment]
Hmmm... I can see now that this line hasn't been changed in the latest release, 2.3.3. So maybe I'm just using the master branch although it shouldn't work.

**Comment by deargle** [comment]
My guess is that your heroku is installing psiturk 2.3.3, but your
custom.py was generated with master.

**Comment by Speldosa** [comment]
Yes, that's exactly what happened. I installed the 2.3.3 release locally, created a new example, and copied the Custom.py file to my project, after which everything worked as expected.
