### ISSUE TITLE
The download_datafiles command gives me several errors

### ISSUE THREAD

**Issue by Speldosa** [NYUCCL/psiTurk#375]
I'm running psiTurk version 2.3.3 locally and psiturk on Heroku (which I guess means it fetches the latest pip version, that is 2.3.3). When trying to download my data using the `download_datafiles` command I first get a bunch of lines looking like this but with different data:

`('Error reading record:', Subject(uniqueid|uniqueCodeForParticipantThatIhaveRemovedHere, condition|0, status|5, codeversion|1.0))`

and eventually, I get this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cmd2.py", line 2476, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python3.6/dist-packages/cmd2.py", line 2675, in onecmd
    stop = func(statement)
  File "/usr/local/lib/python3.6/dist-packages/psiturk/psiturk_shell.py", line 616, in do_download_datafiles
    ret = "".join([contents[k](p) for p in query])
TypeError: sequence item 23: expected str instance, bytes found
EXCEPTION of type 'TypeError' occurred with message: 'sequence item 23: expected str instance, bytes found'
To enable full traceback, run the following command:  'set debug true'
```

Setting the debug to true makes no difference.

This is a database that I've used this whole year, so data have been gathered with different versions on PsiTurk, including the latest one.

What's happening here? I've seen that this has been discussed in issue #79 and somehow solved(?) in pull request #80 but I never quite understood how it was fixed there. Should this happening and how should I get around it?

**Comment by Speldosa** [comment]
Ok, I've been testing some more. When setting up a new example via `psiturk-setup-example` I get errors as well. If running `download_datafiles` on the example before running it, I get three empty csv files (as expected). However, if I run `download_datafiles` after having gone through the experiment once (which I start up by running `debug`), I get the following errors:

```
('Error reading record:', Subject(uniqueid|debugDEMG12:debugP8G458, condition|0, status|2, codeversion|1.0))
('Error reading record:', Subject(uniqueid|debugDEMG12:debugP8G458, condition|0, status|2, codeversion|1.0))
('Error reading record:', Subject(uniqueid|debugDEMG12:debugP8G458, condition|0, status|2, codeversion|1.0))
```

**Comment by deargle** [comment]
You'll need to write your own download script using sqlalchemy and python.
There are no unit tests for do download datafiles, and i'm slammed with
class prep. Docs have an example fetch and analysis script somewhere. You
can also import psiturk and psiturk.config and psiturk.models into your
script to be able to query Participant table for convenience, if you're
fancy.

**Comment by jacob-lee** [comment]
My own recommendation is to write code in custom.py to setup a table(s) to
structure data exactly how you'd like it, and custom routes to save data to
that table, with custom export scripts if needed (in many cases a simple
export of table to csv would be sufficient)

Psiturk's strategy of fitting all an assignments task/questionnaire data in
a single datastring column and row might be reasonable as a one size fits
all strategy, but it's limitations can quickly become apparent when doing
anything remotely complicated.

Jacob

**Comment by Speldosa** [comment]
I've been looking at this, but haven't solved it yet. However, for anyone who has the same problem, an ugly fix is to simply use version 2.2.4 for whenever you need to run the `download_datafiles` command and then go back to the newer version for testing and running the experiment locally.

**Comment by deargle** [comment]
@Speldosa you're able to use `python3.6` with psiturk 2.2.4? I think the error has to do with string encoding, but only python3 is complaining about that right now. psiturk 2.3.5 with python 2.7.15 is able to run `psiturk download_datafiles`

**Comment by deargle** [comment]
@Speldosa https://github.com/NYUCCL/psiTurk/commit/7ec65a00a61f5976c664bd8b8453238b5f4a769c fixes the encoding problem
