### ISSUE TITLE
worker bonus doesn't do anything

### ISSUE THREAD

**Issue by anselmrothe** [NYUCCL/psiTurk#377]
I can't get the `worker bonus` command to work. `psiTurk version 2.3.2`

`[psiTurk server:on mode:sdbx #HITs:0]$ worker bonus --auto --all --reason Thanks` doesn't return any message and also doesn't change any status in the database.

The database has participants with status 4 or 5; and bonus values are filled in.

I've tried various variants 
- order of the arguments
- `--all` vs. `--hit` 
- own experiment and `psiturk-example`
- MySQL database and sqlite:///participants.db
- sandbox and live

... always the same no-result.

(I've credited many bonuses in the past under older psiTurk versions.)

Any ideas? Thanks in advance.

---
EDIT: `Python 2.7.13 -- Enthought, Inc. (x86_64)`

**Comment by jacob-lee** [comment]
Just FYI, I also had trouble getting this command working recently. I ended
up just running some boto3 scripts.

**Comment by deargle** [comment]
Please confirm whether the bug also affects 2.3.3

I know that I screwed up the versionong, but anything > 2.3.0 included a
massive api rewrite as part of the support for python3.

**Comment by anselmrothe** [comment]
Can confirm, I get the same null behavior under `psiTurk version 2.3.3`.

**Comment by anselmrothe** [comment]
Thanks!

I installed psiturk from the `python2` branch, `worker bonus` works as expected now. 

I tested it with `--reason Thanks` (worked), `bonus_message = "Thanks for participating!"` in config.txt (worked), and nothing specified (which triggered the shell prompt).
