### ISSUE TITLE
psiturk installed (I think) but not recognized by system

### ISSUE THREAD

**Issue by zpkilpat** [NYUCCL/psiTurk#378]
I've installed psiturk using pip on Mac OS X, and it appears in /Library/Python/2.7/lib/python/site-packages/
However, when I try to find it using "which psiturk", it is not found.
When I try to run it using "psiturk-setup-example" I get "command not found"
Same if I simply run "psiturk" from the command line.

Any advice? I've tried uninstalling reinstalling. Any suggestions on what to try would be appreciated.

**Comment by deargle** [comment]
This suggests that psiturk was not installed to a folder on your $path. use a virtualenv. Closing as not a psiturk issue.

**Comment by deargle** [comment]
Edit: closing as not a psiturk issue that I can possible replicate because I do not have a mac, and things work well on virtualenvs.
