### ISSUE TITLE
Error 1018 + psiturk dashboard numbers are off

### ISSUE THREAD

**Issue by yang-yangfeng** [NYUCCL/psiTurk#379]
I received a message from a worker saying they saw an error 1018 on HIT 3B9XR6P1WGUTUW7OS0M9FN4VFXDJBA

I see that this corresponds to "hit_not_registered_with_ad_server"

Others have successfully submitted the task, so this doesn't seem like it can be right. But it does seem like there is an issue associated with this HIT - I created it with 10 jobs available, yet it says that there are 14 completes in the dashboard. In the psiturk shell, hit list shows the correct max

<img width="376" alt="Screen Shot 2019-09-11 at 3 33 18 PM" src="https://user-images.githubusercontent.com/16638655/64733000-81938100-d4a9-11e9-8a61-2cb13cb7e9af.png">
<img width="544" alt="Screen Shot 2019-09-11 at 3 31 44 PM" src="https://user-images.githubusercontent.com/16638655/64733005-85270800-d4a9-11e9-9fb6-dafb9695dc55.png">

**Comment by yang-yangfeng** [comment]
I extended the HIT so now the max has gone up to 12, FYI

**Comment by deargle** [comment]
* the psiturk ad server is unreliable, see https://github.com/NYUCCL/psiTurk/issues/350
* the counts aren't "off" -- rather, the way that mturk reports it can be confusing and unexpected. See https://github.com/NYUCCL/psiTurk/blob/465f86bd3ceb1b0f1f9a4ab8969935ef407b9faa/psiturk/dashboard/templates/dashboard/hits/list.html#L113-L115 for some footnotes explaining the situation.
