### ISSUE TITLE
psiturk shell is painfully slow

### ISSUE THREAD

**Issue by fredcallaway** [NYUCCL/psiTurk#380]
After upgrading to 2.3.2, I find that the shell is extremely slow. Switching modes, posting HITs, and approving/bonusing workers are all affected, sometimes taking more than 5 minutes.

I did some digging and it looks like this the time is spent in the `_get_hits` function. A big and easy improvement we can make is to move the `self._get_local_hitids()` call outside of the list comprehension. Currently, a separate database call is made for each HIT. This filtering takes ~109 seconds out of the total 159 seconds that the function takes to execute (for me, at the moment).

However, the 50 seconds spent on `self.amt_services.get_all_hits()` is still not great. So perhaps we should use a different approach altogether. Specifically, is it really necessary to first fetch all the HITs and then filter? Why can't we start with the list of local hitids and then filter out the ones that Amazon doesn't know about using [`get_hit`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/mturk.html#MTurk.Client.get_hit)?

Perhaps I'm missing something. If not, I will go ahead and make a pull request following with the second approach. I will maintain the call signature for `MTurkServicesWrapper._get_hits`, but I will implement a separate `_get_my_hits` method that will be called when `all_studies` is False (to replace the current filtering method)

**Comment by deargle** [comment]
Quick response because about to run off, but:

mb on _get_local_hitids being called over and over, yes, let's move that out.

Unfortunately, there's not an AMT call for multiple hits besides get_all_hits. It starts getting reeeeally slow when there are a lot of hits for one account. The kicker is that only reason that get_all_hits is being called is to update the HIT count in the prompt.

local hitids would be great to use -- the question of whether it makes things faster is whether the total number of calls would be more or less. get_all_hits has to paginate, which is why I think it can take a long time. If one set of creds is being used across many many studies, or if there are a lot of "deleted" hits hanging out in the local table, then I think that that would be slower than get_all_hits.

Ideally, we can just wholly rely on the local hitids table, and never automatically make a call out. I wouldn't mind that approach. But to do so, the hitids table will need to store more info about the hit -- at very least, the mode -- if it's going to still be used for the prompt. And, there would have to be logic in place to delete and expire a hit from the local_hits table. Gets a bit messy which is why I haven't done it. 

We could also maybe just drop the hit count from the prompt, and only display it if explicitly requested.

(Why not 2.3.4?)

**Comment by fredcallaway** [comment]
Here's a sketch of an implementation for the direct non-filtering approach
```
    def _my_hits(self):
        for hitid in self._get_local_hitids():
            if hitid.startswith('debug'):
                continue
            try:
                response = self.amt_services.mtc.get_hit(HITId=hitid)
                yield self.amt_services._hit_xml_to_object([response['HIT']])[0]
            except: # specify error type
                pass # this is equivalent to what we currently do. Is it what we want?
```

**Comment by fredcallaway** [comment]
2.3.4?

https://github.com/NYUCCL/psiTurk/blob/465f86bd3ceb1b0f1f9a4ab8969935ef407b9faa/psiturk/version.py#L1

**Comment by fredcallaway** [comment]
OK so the quick fix is easy (#381)

I know for sure that in my case multiple boto calls to get_hit would be faster than the one call to list_hits. Here are some timings that I got by dropping into an IPython shell at the top of `_get_hits`:

*Getting all hits*
```
>>> %time response = self.amt_services.get_all_hits()
CPU times: user 3.57 s, sys: 326 ms, total: 3.9 s
Wall time: 46.5 s
>>> len(response.data)
4418
```
That's about 10 millisecond per hit.

*Getting hits individually*
```
>>> %time xs = [self.amt_services.mtc.get_hit(HITId=h.options['hitid'])
                for h in response.data[:1000]]
CPU times: user 4.57 s, sys: 256 ms, total: 4.82 s
Wall time: 59.5 s
```
That's about 60 milliseconds per hit. So you definitely get an advantage by paginating rather than making individual calls... but the advantage is surprisingly small. I imagine most people don't manually delete HITs, so list_hits is returning all hits posted in the last 120 days. My intuition is that for most labs, the total number of hits posted in the last 120 days will be well over 6 times the number of hits posted (ever) for a single study. If so, then getting hits individually will be faster.

I agree that trying to manually manage the HIT table is more effort than it's worth.

I also agree that the hit counter should be removed or made optional (through a config setting). But I think it's still worth making it faster for those who want it (and for the `hit list` command).

**Comment by deargle** [comment]
Python version management albatross, I'm using the "python2" branch for
hotfixes to 2.x.x, and master is now python3 only. Psiturk v3 will be
released from master. I really need to update the readme etc saying as much.

https://github.com/NYUCCL/psiTurk/tree/python2

Your patch looks good. And you're probably right about the tradeoff
favoring avoiding get_all_hits.

Maybe for psiturk v2, we just do this hotfix plus the switch to get_hit,
and for v3, we do all other things you mentioned, including dropping count
from the prompt.

I'll review and merge hopefully tomorrow. Thanks for looking into this.

**Comment by fredcallaway** [comment]
Unless you want to test get_hit with Python 2, I suggest we only apply the hot fix on the python2 branch and save the get_hit switch for master.

**Comment by deargle** [comment]
@fredcallaway before I pip-release, can you install and test from head of https://github.com/NYUCCL/psiTurk/tree/python2 branch?

**Comment by fredcallaway** [comment]
I can’t install psiturk out of the box because of readline version
incompatibility. I think the change I made is pretty much impossible to be
wrong, and it does work with version 3 for sure.


On September 20, 2019 at 12:05:29 PM, Dave Eargle (notifications@github.com)
wrote:

@fredcallaway <https://github.com/fredcallaway> before I pip-release, can
you install and test from head of
https://github.com/NYUCCL/psiTurk/tree/python2 branch?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NYUCCL/psiTurk/issues/380?email_source=notifications&email_token=AB4ETFF73BESI53WDP4WVA3QKTYENA5CNFSM4IYDY5J2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7HFHUY#issuecomment-533615571>,
or mute the thread

**Comment by deargle** [comment]
released v2.3.5 to pip. thanks again.

**Comment by fredcallaway** [comment]
Is there a branch for version 3? Where should I pull request the `_my_hits` patch?

**Comment by deargle** [comment]
version 3 will be released from master branch
