### ISSUE TITLE
Hit list and worker list not working when using psiturk with heroku.

### ISSUE THREAD

**Issue by esandov4** [NYUCCL/psiTurk#384]
I am using a dockerized psiturk application in windows with my experiment running on a heroku app instead of psiturk's web server. I am able to create hits in sandbox mode and live mode, and prior to anyone completing the hit, I can check on the hit status with hit list. After some turkers have completed the experiment(I checked by pulling from a backup to a local database), then I can no longer use hit list or worker list.
For reference, these are the errors I'm getting. I am able to create hits and obtain my real balance so there's nothing wrong with connecting to AWS servers.
When I type worker list:
[psiTurk server:on mode:sdbx #HITs:0]$ worker list
KeyError('assignments',)

[psiTurk server:on mode:sdbx #HITs:0]$ hit list --active
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2476, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 2675, in onecmd
    stop = func(statement)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/psiturk_shell.py", line 76, in helper_fn
    return func(self, opt)
  File "/usr/local/lib/python2.7/dist-packages/psiturk/psiturk_shell.py", line 1059, in do_hit
    arg['--all-studies'])
  File "/usr/local/lib/python2.7/dist-packages/psiturk/psiturk_shell.py", line 199, in hit_list
    all_studies)).data['active_hits']
KeyError: 'active_hits'
EXCEPTION of type 'KeyError' occurred with message: ''active_hits''

Due to this issue, I can only check on the status of my hit by looking at the postgres database connected to the heroku app to check how many experiments have been run. Additionally, I am unable to compensate any turkers due to being unable to use the worker command.

**Comment by deargle** [comment]
What version psiturk? Upgrade? L199 in psiturk_shell on psiturk 2.3.6 doesn't match yours from the error message: https://github.com/NYUCCL/psiTurk/blob/v2.3.6/psiturk/psiturk_shell.py#L199

**Comment by esandov4** [comment]
My bad. I thought I had the most recent release. Upgraded to psiturk 2.3.6 and I don't have this issue anymore.
