### ISSUE TITLE
Using zenodo for DOIs for psiTurk

### ISSUE THREAD

**Issue by deargle** [NYUCCL/psiTurk#387]
I'd like to start archiving releases of psiTurk with DOIs to make citation easier. One approach I have used with https://github.com/scikit-tda/kepler-mapper#how-to-cite is to ask that both a paper be cited, as well as a DOI pointing to the source code. Zenodo github hooks provide a DOI for both the overall project, as well as a DOI for each release.

@gureckis and I were talking about who to list as the "contributors" for v2.3 and onward. The approach we came up with is to consider factors like
* number of commits
* lines of code contributions
* recency of contributions
* design decisions

Using recency weighting, there is a bit of a gap in number of commits between alex (111) and others (20s). In view of that, for this DOI and going forward, Todd's proposition, which I support, is to have the "authors" be listed as follows, in the following order: @deargle, @gureckis ,  @alexanderrich , @johnmcdonnell @jbmartin 

The "author" order could be updated for future releases.

Any objections and all in favor? And to the above persons, would you please share your ORCID and affiliation, if any?

**Comment by gureckis** [comment]
Sounds good to me.  My ORCID is https://orcid.org/0000-0002-7139-4778, affiliation is New York University.

**Comment by deargle** [comment]
It is done. Alex, John, Jay, feel free to provide a desired affiliation here, and I'll set it to be used for future releases.

I added a link to the zenodo DOI on the readme, and I also updated the "how to cite" bit at the bottom of the same.
