### ISSUE TITLE
Concerning hit status 

### ISSUE THREAD

**Issue by MicroSTM** [NYUCCL/psiTurk#395]
When I check my hit status, it reads:
	Status: Unassignable 
	HITid: 3R5OYNIC2DJF9YYWBFJCT6KOZ7ITPW             
	max:50/pending:35/complete:0/remain:0 
	Created:2020-01-24 20:33:44+00:00             
	Expires:2020-01-25 20:33:44+00:00
	Is Expired:False

I did get complete responses from 15 subjects, and this makes me wonder if those subjects have been paid since the status said 0 completion. Is this a bug and how can I check if the hits are actually complete and if the turkers are getting paid? My psiturk version is 3.0.0.

**Comment by deargle** [comment]
Not a bug. An mturk oddity, not a psiturk one. See my explanations here:

![image](https://user-images.githubusercontent.com/1174653/73107294-b46b6e00-3eba-11ea-9e6d-134228615af4.png)

**Comment by deargle** [comment]
Also, if you didn't pay them through psiturk, then psiturk would not know that you paid them.

**Comment by deargle** [comment]
Also, 3.0 is the dev version, and is not officially released. Only the packages on pip are declared stable. Although I use 3.0 for my personal uses.

**Comment by MicroSTM** [comment]
Got it! Thanks for the quick response.
