### ISSUE TITLE
How soon?

### ISSUE THREAD

**Issue by kix2mix2** [NYUCCL/psiTurk#401]
So I am trying psiturk these days to see if I can use it with my experiments. I know I can do my experiments on Heroku, I was just wondering how soon is it until the ad server will be up again? Is it soon as in hours, days, weeks?

https://ad.psiturk.org

**Comment by gureckis** [comment]
the ad server is up actually.  the "coming soon" thing is just a random place holder.  in, if you can see that message it usually means it is working
