### ISSUE TITLE
how to test with headless browser in sandbox

### ISSUE THREAD

**Issue by yang-yangfeng** [NYUCCL/psiTurk#402]
I've been using puppeteer to test my task, but I've only been hosting locally in debug mode. Ideally, I'd like to be able to test in sandbox mode, hosting on the server I use for actual deployment (EC2 instance). The issue I'm running into is that if I manually go to workersandbox and accept the HIT, then run my node script to test by going to the "/consent" route, hit agree, I get an error 1010 (already_started_exphit). I tried to see if just having my script do everything, starting from logging in through accepting and proceeding with consent/task - but I haven't been able to evade captcha (even after changing UserAgent to match my regular chrome browser). I then tried setting allow_repeats to true, but I see now that this doesn't change the cases where experiment is begun and then closed. Weird thing is if I hit begin, consent pops up, agree to consent, and then close the pop up - I can still do it again and enter the task just fine. Any easy solutions that I'm missing?

**Comment by deargle** [comment]
Try deleting all records for your workerid from your database and trying
again.

**Comment by yang-yangfeng** [comment]
Yeah I also did that - again, I don't get the error if I just am doing it with normal Chrome, only with my script using puppeteer (which relies on headless chromium)

**Comment by deargle** [comment]
Sorry, I have no idea about this stuff. Going to close because it's probably not a psiturk code bug
