### ISSUE TITLE
Recommended Linux Distribution?

### ISSUE THREAD

**Issue by jk31** [NYUCCL/psiTurk#403]
Hello,

this project looks very promising and I would like to test it for my work.

I just installed a clean Linux Mint distribution, but I get several errors no matter what I try.

For example, I tried `pip install psiturk` and `sudo python setup.py install`

https://gist.github.com/jk31/b7d82e41c5a8612e44f54bd03cb579dd

**Comment by deargle** [comment]
https://stackoverflow.com/a/54833684/5917194

looks like `pip install psiturk` is failing for you because of pip's `wheel` package being messed up. Read through the SO thread above.

`python setup.py install` is not working for you because you're using python2.7 and git master is python3 only.
