### ISSUE TITLE
blank webpage in work sandbox

### ISSUE THREAD

**Issue by haoxue-fan** [NYUCCL/psiTurk#404]
I am just testing the psiturk-example in amazon worker sandbox. Though it could run locally and hits can be created, but when I click 'Accept', the experiment page is blank and after a while, an error will show up: 
<img width="1757" alt="Screenshot 2020-03-09 19 35 25" src="https://user-images.githubusercontent.com/42018862/76272530-06413b00-6252-11ea-9136-7029c8572889.png">

I have googled a while and found some information both in google groups and  #306 .  However, none of them could solve my problem. I am running the server on a wired university computer and I have tried both using 0.0.0.0 or public IP address in the config.txt (or is that the public IP address shouldn't be used this way?) My computer doesn't have firewall turned on. So I am really confused and don't know what I could do to solve this problem.

Thank you in advance!!

**Comment by deargle** [comment]
Talk to someone at your uni who understands networking and who can help you
get a public ip address for the computer from which you want to run psiturk.

**Comment by haoxue-fan** [comment]
@deargle 
Thanks for the prompt reply! However, I have checked with IT service in my university and I am using the write public ip address. The experiment page is blank both on chrome and safari, and the server log's info is like this:

> [2020-03-12 10:47:52 -0400] [51726] [CRITICAL] WORKER TIMEOUT (pid:51760)
> [2020-03-12 10:47:52 -0400] [51726] [CRITICAL] WORKER TIMEOUT (pid:51763)

When I use inspection mode in Chrome I saw a warning like this but I am not sure whether this is the problem..

> A cookie associated with a cross-site resource at http://psiturk.org/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Any idea about what the problem is happening...? sorry for the inconvenience and thank you for your help in advance!!

**Comment by haoxue-fan** [comment]
update: I bypassed the problem by using heroku instead. it seems to me maybe the psiturk ad server is temporarily down (at least for me)
