### ISSUE TITLE
Ad server account request

### ISSUE THREAD

**Issue by jennhu** [NYUCCL/psiTurk#410]
Hi psiTurk! I requested an account on the psiTurk ad server and got an invite code. But it's been 3 days, and I still haven't received the verification email. I've checked my spam folder as well.

Is there a way to manually resend the email?

**Comment by deargle** [comment]
I'm not involved with the ad server, but I know that the plan is to sunset the ad server. Better to self-host an ad using a service such as Heroku. No need for a psiturk.org account in that case.

**Comment by jennhu** [comment]
Ok, thanks.
