### ISSUE TITLE
I registered to psiturk.org but did not get verification email. Can't login.

### ISSUE THREAD

**Issue by halelyb** [NYUCCL/psiTurk#417]
Hello,
I have requested an account, got my registration code and used it to register.
When I try to log in I get an error message:
"Sorry, this account has not been verified. Please check your email for the verification link."

I tried to do reset password process and got an email for that.
Is there any way to check this situation?

Thanks

**Comment by deargle** [comment]
Shrug. psiturk.org is going to be sunset in favor of users finding their own https hosting, via for example heroku. I'm going to close this therefore. Recommend following heroku setup instructions, more stable anyhow than psiturk ad server.
