### ISSUE TITLE
Error when `hit extend` the duration

### ISSUE THREAD

**Issue by yunshiuan** [NYUCCL/psiTurk#421]
I tried to extend the duration of a hit but encountered an error.
`hit extend <HITid> --expiration 60`
> Response(Operation: extend_hit | Status: error | Exception: 'AmtServicesSuccessResponse' object has no attribute '__getitem__')

Note that `hit extend <HITid> --assignment 10` works fine.

I am using psiTurk version 2.3.8 with python 2.7.17.

**Comment by deargle** [comment]
Thanks for the report. I think the first call actually worked, btw. Just an
error in the feedback.

**Comment by yunshiuan** [comment]
That doesn't work for me though. The duration does not increase after I run `hit extend <HITid> --expiration 60`.

**Comment by yunshiuan** [comment]
So before this problem is solved, I wonder if I could just create another hit with the same `ad_group` string, and safely assume that workers would not repeat in participation? That is, workers that have already taken one of the hits in the same ad_group, would not be able to take another hit in the same ad_group. Is that right?

**Comment by deargle** [comment]
Yes, they would be blocked. ad group doesn't have anything to do with it --
they would be blocked from retaking. Your local database is consulted.

**Comment by deargle** [comment]
v2.3.9 should be on pip in a few minutes, with a fix for this. Thanks again for reporting.

**Comment by yunshiuan** [comment]
Thank you! It seems like it only works for unexpired hit. Is that correct? Is there a way to makes an expired hit unexpired again?

**Comment by deargle** [comment]
You know, I'm not sure, I've never tried that. I always just create a flood
of micro hits, creating new ones if the old ones expire if I need more data.
