### ISSUE TITLE
An error with worker approve <assignment_id>

### ISSUE THREAD

**Issue by yunshiuan** [NYUCCL/psiTurk#424]
I ran into an error when I tried to approve an assignment.
```
worker approve <assignment_id>
Approving specified submissions for the current study...
Response(Operation: approve_assignment_by_assignment_id | Status: error | Exception: An error occurred (RequestError) when calling the ApproveAssignment operation: This operation can be called with a status of: null (1591073846654))
```
This assignment initially had a status code '1' in the database, but he/she did actually complete the task. So I changed the status code to 4 to label the assignment as submitted. However, when I tried to approve the assignment, it failed with the error message above.

I am using psiTurk version 2.3.9 with python 2.7.

**Comment by deargle** [comment]
Status 1 indicates _big_ problems with the worker. Your psiturk db doesn't
even acknowledge that they completed the task, let alone mturk. It can
happen sometimes that psiturk thinks a worker completed a task when
actually something failed on the mturk end, and you'd see that error that
you saw. But yeah that assignment that you hand edited definitely did not
complete it. From psiturk perspective, they didn't even _start_ the task!
That would be status 2.

**Comment by yunshiuan** [comment]
I see. I wonder Is there a way that I can pay the worker regardlessly? The worker's data has been well recorded except there's a bug the prevented him/her to the submit bottom.

**Comment by deargle** [comment]
Look into psiturk whoopsyall project.

**Comment by yunshiuan** [comment]
Thank you! I noticed that there are quite a few workers with status code 1, although most of them have status code 4. I wonder if you could provide some thoughts on what's the reason for this. Could it be due to the fact that the server's resource was used up?

**Comment by deargle** [comment]
Closing, see google group for more troubleshooting help pls
