### ISSUE TITLE
"NoMturkConnectionError" - are AWS creds necessary?

### ISSUE THREAD

**Issue by surveybott** [NYUCCL/psiTurk#427]
Hello,

I'm running psiTurk v2.3.9 and get the following error message when attempting to start the shell:

> NoMturkConnectionError: Sorry, unable to connect to Amazon Mechanical Turk. AWS credentials invalid.
> You can still use the psiturk server by running non-AWS commands such as:
> - `psiturk server <subcommand>`
> - `psiturk server start`
> - `psiturk server stop`
> - `psiturk debug -p`

I have not put AWS credentials in .psiturkconfig, but I'm unable to run the non-AWS commands listed above. Is it possible to use the shell for local server commands like starting the server, download_datafiles etc.?

Thanks!
Jeff

**Comment by deargle** [comment]
I think I screwed up the logic for that check, todo.

**Comment by KovenYu** [comment]
Hi,

I have a similar problem. I also use 2.3.9. I follow the [quick start](https://psiturk.org/quick_start/) and enter the AWS access key id, aws secret access key, and those of psiturk. But I got the same error prompts when I type "psiturk" in ~/psiturk-example/ (that is, I cannot see the greeting prompts as indicated in Step 4 in the [quick start](https://psiturk.org/quick_start/)).

Any idea to troubleshoot this?

Thank you!
Koven

**Comment by deargle** [comment]
v2.3.11, just released to pip, should patch this. master branch already had the patch. reopen if it still seems broken, thanks for reporting.

**Comment by Speldosa** [comment]
I'm on 2.3.11 (psiturk --version confirms this), and I get the same command suggestions as above.

**Comment by deargle** [comment]
You _should_ get the same commands as shown above, but OP reported that even those commands didn't work.

**Comment by deargle** [comment]
btw I can't remember if I fixed the suggestion to say `server on` like it should be, instead of `server start`

**Comment by Speldosa** [comment]
It says that you can use 'psiturk sever start', which doesn't work (Invalid command!). However, 'psiturk sever on' works.
