### ISSUE TITLE
Running PsiTurk on WSL for development

### ISSUE THREAD

**Issue by luka-ve** [NYUCCL/psiTurk#431]
Currently the docs for the [installation steps](https://psiturk.readthedocs.io/en/stable/install.html#windows) mention that PsiTurk is not available for Windows. Moreover, it is suggested to _not_ host experiments from within virtual machines. While that's true, it might be helpful to make beginner developers aware of [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) (WSL). This could help non-technically minded folks set up a local development environment relatively quickly without dealing with VMs or dual-booting.
Using WSL also allows people to use tools they already know, as all experiment files can live on the Windows file system.
I already tested this and PsiTurk will happily run experiments locally using `debug`. I tested this with both an experiment folder in the WSL file system and on a mounted Windows drive.

I would be happy to write a short section if could seem useful for some users.

**Comment by deargle** [comment]
https://github.com/NYUCCL/psiTurk/pull/428 is this what you had in mind? Any ideas for improving it? Docs are a mess and when I think about the work they need I curl up into a ball and sob, sorry I haven't merged stuff into there recently.

**Comment by luka-ve** [comment]
Yes, that's exactly what I had in mind! I searched issues for `WSL`, but that issue didn't show up. #428 gives plenty of information, I see.
No worries at all. I am new to PsiTurk, but when I feel more confident I hope I will be able to contribute. :)
