### ISSUE TITLE
pip install from requirements.txt fails

### ISSUE THREAD

**Issue by jacob-lee** [NYUCCL/psiTurk#439]
```
pip install -r requirements.txt 
```

generates the following error:

```
...
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

boto3 1.9.253 requires botocore<1.13.0,>=1.12.253, but you'll have botocore 1.12.252 which is incompatible.
```

**Comment by deargle** [comment]
You said you're on python 3.8, right? I don't have test configured currently to test against 3.8, but I can add it.

**Comment by deargle** [comment]
Hmm I'm not seeing that particular error in the travis py38 run, https://travis-ci.org/github/NYUCCL/psiTurk/jobs/733486580. Looks like it's using python 3.8.0 and pip 19.3

**Comment by jacob-lee** [comment]
I think I'll try using a few different versions of python, see what I come
up with.

**Comment by deargle** [comment]
When you do, note your pip versions, too, pls

**Comment by deargle** [comment]
I'm going to close this, but feel free to open it again when you replicate it.

**Comment by jacob-lee** [comment]
Actually it looks like I'm not able to replicate; I think this may have something to do with how I set up my Pycharm environment to handle the requirements.
