### ISSUE TITLE
code quality issues in psiturk_shell.py

### ISSUE THREAD

**Issue by jacob-lee** [NYUCCL/psiTurk#443]
I noted several issues with psiturk_shell.py, including, but not limited to the following:

- PsiturkNetworkShell docstring says extends PsiturkShell, but it doesn't extend PsiturkShell, ti extends, Cmd. PsiturkShell looks like it doesn't exist.
- PsiturkNetworkShell::do_quit (line 176) doc string says its over-riding do_quit for network clean up. But that isn't true
- PsiturkNetworkShell::do_quit (line 377) is defined a second time in the same class.
- PsiturkNetworkShell::hit_create (line 481). The regex has a warning about invalid escape sequence. Probably just needs to be prepended with r (to make regex)
- Most doc-strings should be converted to triple """ form
- self.poutput is not defined in `run`
- Unresolved reference i do_list_qualifications (line 779)
- PsiturkNetworkShell::do_worker: results may be used before assignment
- Potential issues with variables that can be references before assignment
- Multiple references to undefined variables

**Comment by deargle** [comment]
Thanks for tidying this.

> PsiturkNetworkShell docstring says extends PsiturkShell, but it doesn't extend PsiturkShell, ti extends, Cmd. PsiturkShell looks like it doesn't exist.

That's correct. There used to be a "cabin mode" that PsiturkShell was used for, and then the "connected" mode that PsiturkNetworkShell was used for, but at some point I got rid of the cabin mode after I made it possible to execute commands without starting the interactive prompt. And yeah some functions got defined twice and my tests didn't catch them.

What are you using for code quality checks? Pycharm? I should set up something like that...

**Comment by deargle** [comment]
And yeah, docstrings have been long neglected...

**Comment by jacob-lee** [comment]
PyCharm. I used to do all my dev in Emacs, but I got tired with fiddling with it. PyCharm works very well (and handles the JavaScript stuff pretty well too). Also I discovered that they give out the pro version of all Jet Brain's IDEs free with an academic license.
