### ISSUE TITLE
error 1015, heroku app

### ISSUE THREAD

**Issue by yang-yangfeng** [NYUCCL/psiTurk#445]
I'm moving over from ec2 to heroku. The app works at monosov-imt.herokuapp.com. However, when I launch a sandbox HIT, it will not load the ad and instead says: 
```
Experimenter error: Experiment server unreachable
Sorry, the experiment server is currently unreachable. Please contact the requester to let them know that their server is offline!

If you would like to receive partial compensation or feel you have reached this page in error, please email monosovlab.mturk@gmail.com and send the following information:

Error: #1015
HITID: #[u'3VGZ74AYTIF2DZ9TYUV8O485Z2BGC4']
WorkerId: #[u'A1VUPOKC3CII5P']
```

Followed the instructions here: https://psiturk.readthedocs.io/en/latest/heroku.html. 
Ran this script to set heroku settings: https://github.com/NYUCCL/psiTurk/blob/908ce7bcfc8fb6b38d94dbae480449324c5d9d51/psiturk/example/set-heroku-settings.py.

Here's my config.txt
```
[HIT Configuration]
title = InfoSeekingTask
description = InfoSeekingTask
amt_keywords = study, psychology, experiment
lifetime = 1
us_only = true
approve_requirement = 95
contact_email_on_error = monosovlab.mturk@gmail.com
ad_group = InfoSeekingTask
psiturk_keywords = infoseekingtask
organization_name = Monosov Lab
browser_exclude_rule = MSIE, mobile, tablet

[Database Parameters]
database_url = postgres://xx@ec2-xx-xx-xx-xx.compute-1.amazonaws.com:xx/xx
table_name = infomegatask

[Server Parameters]
host = 0.0.0.0
port = 22362
cutoff_time = 180
logfile = server.log
loglevel = 2
debug = true
threads = 1
ad_location = https://monosov-imt.herokuapp.com/pub
use_psiturk_ad_server = false

[Task Parameters]
experiment_code_version = 4.4.1
num_conds = 1
num_counters = 8

[Shell Parameters]
launch_in_sandbox_mode = true
```

I'm probably missing a step somewhere to set permissions or something, but not able to find the problem after much digging. Would really appreciate some pointers on where to look for issues.

**Comment by deargle** [comment]
This would be better on the google group, so I'm going to close the issue here for notification sanity.

* run `heroku logs` to see why it's crashing
