### ISSUE TITLE
codeversion needs quotations in the exp.html

### ISSUE THREAD

**Issue by afdreher** [NYUCCL/psiTurk#447]
I was just building a new version of the psiturk example to verify my local changes, but the new codeversion variable breaks the example.  The reason is `var codeversion = {{ codeversion }}; // a number indexing counterbalancing conditions`  needs to be `var codeversion = "{{ codeversion }}"; ...`  because otherwise JS will interpret the semantic version, such as 0.0.1, as an invalid number, even though the rest of the code correctly expects it to be a string.

Additionally, the copy and paste comments need to be modified to reflect the purpose of the variables.

**Comment by deargle** [comment]
Closed by
