### ISSUE TITLE
Feature proposal: support for manual Qualification Types

### ISSUE THREAD

**Issue by decodyng** [NYUCCL/psiTurk#458]
Not sure if this is the right protocol, but: for a project I'm working on, we needed support for attaching a manually-created Qualification Type to our HIT (just the attaching; assume you've done the actual creation of the Qualification elsewhere), and I've put together a (quite small line-change) branch in my fork that I believe is doing this successfully. Is this something the maintainers might be interested in as a PR?

**Comment by deargle** [comment]
It's already done on master branch, actually.

**Comment by decodyng** [comment]
So, I thought this, and closed the Issue, and then realized it isn't actually done in the way I'd need, with a numeric rather than binary Qualification (that is, the kind generated by a QualificationTest)

**Comment by decodyng** [comment]
Based on the fact that the master branch only checks for `Exists` rather than any kind of `GreaterThanOrEqualTo` logic that you'd need to grade a qualification test of the kind we're making for our project

https://github.com/NYUCCL/psiTurk/blob/master/psiturk/amt_services.py#L321

**Comment by jacob-lee** [comment]
This is actually supported in a limited way now in the dev version on
GitHub.

Jacob

**Comment by deargle** [comment]
A workaround is to create a new binary qualification based on your
continuous qualification. I'm hesitant to add code complexity when that
flow is possible.

**Comment by evankirkiles** [comment]
@deargle How would one go about doing that, creating a binary qualification based on an existing qualification? Could you point me to relevant documentation that says this is possible?

**Comment by deargle** [comment]
Closed by https://github.com/NYUCCL/psiTurk/pull/493 (authored by @evankirkiles)

As for the question of creating a binary qual from a continuous one, I was thinking of a python boto3 script that does something like: 

1. create a binary qualification, starting with no workers assigned
2. fetch all workers with any setting for a given qualification
3. loop over those workers. if qualification value > than some value, grant them the binary qualification created in step 1
