### ISSUE TITLE
Prevent a HIT from being submitted automatically if questions answered incorrectly

### ISSUE THREAD

**Issue by jackransomlovell** [NYUCCL/psiTurk#459]
Hi everyone!

I am currently building an experiment in jsPsych and plan to interface with Mturk via psiTurk and Heroku. Currently, I have two attention checks, and if a participant fails the attention check, I would like to end the experiment and reject their HIT automatically. The first is a loop to ensure their audio is working. Please see the code below.
``` javascript
var audio_test = {
    timeline:[
        {
            type:'audio-keyboard-response',
            stimulus: function(){
                // select audio file at random
                var audio_file = jsPsych.randomization.sampleWithReplacement(audio,1);
                audio_stim.push(audio_file);
                return audio_file
            },
            choices: jsPsych.NO_KEYS,
            trial_ends_after_audio:true
        },
        {
            type:'html-button-response',
            stimulus:'What number did the person say in the previous audio clip?',
            choices: ['0','1','2','3','4','5','6','7','8','9'],
            on_finish: function(){
              // end the experiment if they don't get the answer right the first 50 times
              if(parseInt(jsPsych.currentTimelineNodeID().slice(Math.max(jsPsych.currentTimelineNodeID().length - 2, 1))) > 50). 
              {
                jsPsych.endExperiment('You failed the audio trial. Your HIT will not be completed please exit the page.')
                } 
            }
        }
    ]
}
```

So currently, the `on_finish` function checks to see if they are still below 50 tries. If this number exceeds 50 I would like to kick them from the experiment, return the HIT to Mturk, reject their HIT, and NOT submit their data to MTurk. 

The second check is simply a slider that asks the participant to place the value of the slider at the start or the end of the scale. If they get this question wrong more than two times, or they take longer than 15 seconds to answer the question, I would like to kick them in the same way. I do not have the code written out but I have a feeling it is a similar solution to the problem above. 

I have a feeling it can just be a simple call to the jsPsych `external-html` plugin, and then simply redirect the participant to an html page explaining their rejection, but I am unsure what the html file that details the rejection should entail to i.) not record their data and ii.) return the HIT to MTurk. Thanks in advance for the help!!

**Comment by deargle** [comment]
You can't reject their submission because they haven't actually submitted
anything yet. You also can't submit on their behalf -- has to be a
user-triggered event. The best you can do is flag them in the psiturk db as
having failed, and then _tell_ them to return the assignment, because
there's no way you'll pay them at this point.

**Comment by jackransomlovell** [comment]
Thanks, @deargle! Would I be able to send an error page instead somehow? Looking to achieve this with the psiTurk.js API but not seeing anything...

**Comment by deargle** [comment]
You could show error html just like you would show any html in a standard
psiturk experiment, with showPage or whatever it is, on tablet rn. More
complicated would be to fiddle with custom.py and send the user to a custom
route, like /complete does in psiturk.js . With a custom route, you could
do whatever to the database before telling them they'd failed.
Alternatively, you could just flag them as a "quitter," I think there's a
line in psiturk.js that does that. Sorry I can't give you more specific
pointers rn.

**Comment by jackransomlovell** [comment]
Thanks, @deargle. I'll work with this a bit more and post a solution if I find one. 
P.S. #skobuffs
