### ISSUE TITLE
Api.psiturk.org ssl cert expired 

### ISSUE THREAD

**Issue by janusgreenb97** [NYUCCL/psiTurk#462]
I am having an issue that when creating hits I will get an SSL error. I tried in real mode and in sandbox, on ec2 instance and on local and all having the same issue. This happened two days ago and before that I can create hits.

My psiturk version is 2.3.11 the latest one, and I have installed certifi.

```
Error during hit creation.
Response(Operation: create_hit | Status: error | Exception: HTTPSConnectionPool(host='api.psiturk.org', port=443): Max retries exceeded with url: /api/ad (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))))

```

That would be really appreciated if anyone can give me some suggestions why this happened. Thanks!!

**Comment by deargle** [comment]
Probably an expired api.psiturk.org cert. You should still be able to
create a non-psiturk-ad-server hit.

**Comment by janusgreenb97** [comment]
Thank you for the prompt response! I don't have my own ad server, is there a way I can update api.psiturk.org cert?

**Comment by deargle** [comment]
No, there's not. See the docs for deploying on heroku.

**Comment by janusgreenb97** [comment]
Thank you! I will look into it. Why did the ssl cert expired? Is it an issue with my psiturk.org account?

**Comment by gureckis** [comment]
the psiturk.org certs were just renewed give it a bit....
