### ISSUE TITLE
ad.psiturk.org Certificate Expired

### ISSUE THREAD

**Issue by mattnulle** [NYUCCL/psiTurk#463]
I'm able to create HITs, but the ad server (https://ad.psiturk.org/) is giving an invalid cert, which prevents users from actually linking to my task and accomplishing the HIT I created. Strangely, I've gotten a couple of Turkers that were able to submit the HIT, and I'm not sure how that would happen. The sandbox ad server (https://sandbox.ad.psiturk.org/) is still giving a valid cert through the beginning of April, so testing a HIT there gives a false sense that it's working.

Let me know if there's any more information I can provide, or if there's something I need to do on my end to start using newer certs. Thanks!

![image](https://user-images.githubusercontent.com/20324034/108527716-9aa88000-72a0-11eb-979e-aad11acebd1c.png)

**Comment by gureckis** [comment]
try now, there was something configured wrong but appears to be fixed

**Comment by mattnulle** [comment]
Yeah, it seems to be working now. Thanks! Psiturk is a great tool, and I appreciate it
