### ISSUE TITLE
sandbox.ad.psiturk.org’s server IP address could not be found.

### ISSUE THREAD

**Issue by Serge-** [NYUCCL/psiTurk#464]
I'm trying to post HIT project to Amazon Mechanical Turk, but seems like something wrong with the server?
A message: "sandbox.ad.psiturk.org’s server IP address could not be found."
Is it any status commands to check server availability?
Thanks.

**Comment by deargle** [comment]
yikes, hold oh. we migrated dns to cloudflare. one sec.

**Comment by deargle** [comment]
okay, it's back on. thanks for reporting, let me know if anything else seems broken.

**Comment by Serge-** [comment]
Thank you, Dave! 
Now it is working.
Thanks for the prompt feedback and issue-resolving!
