### ISSUE TITLE
already_started_exp and WORKER TIMEOUT

### ISSUE THREAD

**Issue by surveybott** [NYUCCL/psiTurk#465]
Hello,

We've been experiencing issues with an experiment, often getting the below error messages about "already_started_exp" and [CRITICAL] WORKER TIMEOUT".

I've checked to make sure the server isn't under too much load (memory, CPU, bandwidth) and that's not the case.

It seems to occur sporadically throughout the experiment in maybe 10-20% of runs. There are two calls to preload images (about 15 MB each) and it doesn't appear to coincide with these calls. 

From `server.log`:
```
2021-03-03 12:41:14,988 already_started_exp (1008)
2021-03-03 12:41:21,074 already_started_exp (1008)
[2021-03-03 12:41:52 +0000] [2834] [CRITICAL] WORKER TIMEOUT (pid:3088)
```

I'd appreciate any help. Our lab is unable to replicate when testing the experiment ourselves.

Thanks,
Jeff

**Comment by deargle** [comment]
This is better for the google group, so I'm going to close, but `already_started_exp` is one of your workers quitting / reloading etc and then trying to start again, but getting blocked. That's a feature, not an error.

And WORKER TIMEOUT refers to gunicorn workers -- one spins up per thread. The only reason I can think of for this to happen is if you have some custom python code that makes a request to an external service that times out. That's what would lead to the above. You can read more about it in the gunicorn does.
