### ISSUE TITLE
psiturk-heroku-config:: command not found

### ISSUE THREAD

**Issue by gbernal** [NYUCCL/psiTurk#481]
Hi there,

I'm following the step to deploy psiTurk with heroku and one of the steps is to run this command psiturk-heroku-config, when I do that I get the error command not found. As a side note when I run psiturk-setup-example works as expected.
My psiTurk version is 2.3.12. Any help would be greatly appreciated 

Thank you
Guillermo

**Comment by gureckis** [comment]
update to latest in pip (e.g., right now it is 3.0.6), I don't believe that command existed back in the 2.3.x era.

**Comment by gbernal** [comment]
@gureckis maybe I miss understood something but I saw in one of the comments here that I shouldn't use 3.0 yet as  there are some issues creating a hit with sandbox, I was having that issue that is why I went to 2.3.12

**Comment by gureckis** [comment]
really hmm... do you have a link to the discussion?  I believe I've first hand experienced 3.0.6 working

**Comment by gbernal** [comment]
@gureckis I believe it was from this thread https://groups.google.com/g/psiturk/c/cYjEmLXy0jk/m/xWAnJ0NeBAAJ but I have a million tab opens as I'm trying to learn how to use psiTurk haha

**Comment by deargle** [comment]
2.x was having troubles creating hits using the psiturk ad server. 3.x
doesn't support the ad server. The latest 2.x has a fix for creating ads
using the psiturk ad server. And Todd is correct, 2.x doesn't have the
psiturk-heroku convenience command. Use the python2 version of readthedocs
if you're trying to use psiturk 2.x to run on heroku, but really that
wouldn't make sense, it's easier to run on heroku using psiturk 3.x. The
only reason to use psiturk 2.x is if you want to use the
going-away-in-a-few-months psiturk ad server.

**Comment by gbernal** [comment]
@deargle Thank you so much for the clarification! and for all the work that is going into psiTurk.
