### ISSUE TITLE
Hit creation fails: Exception: __init__() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by Sumith1896** [NYUCCL/psiTurk#485]
Debug mode is working fine but when I try to launch HITs, I get the following error:

```
[psiTurk server:on mode:sdbx #HITs:0]$ hit create 
number of participants? 1
reward per HIT? 1.00
duration of hit (in hours, it can be decimals)? 10
*****************************
    Max workers: 1
    Reward: $1.00
    Duration: 10.0 hours
    Fee: $0.20
    ________________________
    Total: $1.20
Create sandbox HIT [y/n]? y
Error during hit creation.
Response(Operation: create_hit | Status: error | Exception: __init__() takes exactly 1 argument (2 given))

```

I have narrowed it down to the following line (300) in `psiturk_shell.py`:

```
            create_hit_response = self.amt_services_wrapper.create_hit(num_workers=numWorkers, reward=reward,
                                                                       duration=duration)

            if create_hit_response.status != 'success':
                self.poutput('Error during hit creation.')
                print(create_hit_response)
                return
            else:
                self.maybe_update_hit_tally()
```

Psiturk version: 2.3.6 (also tried with 2.3.11 and 3.x.x)
Python version: 2.7.17 (also tried with 3.6 and 3.7)

I remember having psiturk working with similar configurations in past, any inputs will be really helpful! Thanks!

**Comment by deargle** [comment]
Upgrade to psiturk 2.3.12 and remove all comments from your ad.html, see
google group for a longer thread

**Comment by Sumith1896** [comment]
Thanks @deargle! Issue fixed!

**Comment by kjaeschwartz** [comment]
how do i upgrade to version 2.3.12? I dont wanna do the whole complex process of upgrading to version 3, i just want to be able to run my experiment.

**Comment by deargle** [comment]
pip install --upgrade psiturk==2.3.12
