### ISSUE TITLE
HIT create issue

### ISSUE THREAD

**Issue by kjaeschwartz** [NYUCCL/psiTurk#490]
Whenever i try to create a hit I get this error

Error during hit creation.
Response(Operation: create_hit | Status: error | Exception: __init__() takes exactly 1 argument (2 given))

I have no idea what's wrong. Please help!!!!!!!!

**Comment by deargle** [comment]
You asked the same thing yesterday! See https://github.com/NYUCCL/psiTurk/issues/485
