### ISSUE TITLE
heroku deployment issue

### ISSUE THREAD

**Issue by kjaeschwartz** [NYUCCL/psiTurk#494]
I've been trying to deploy my psiturk program to heroku for a while now. I've gone through the instructions like 10 times but every time when i go to the heroku site I get an application error. When I go to the tail logs it says I have an error 514. To be able to fix that the heroku site said to scale the dynos . But when I try to do that heroku never accepts the command. And when I try to run the program via the amazon site link i get when i create a hit I get a broken web app that says I cant reach the host. At this point I've gone through the instructions so many times I'm sure i got it right. I dont care if the program ends up being on heroku or hosted by mturk like it used to be, i just need it to work. I have  no idea what is wrong or how to fix it.

**Comment by deargle** [comment]
* The experiments _never_ have been hosted by mturk. The psiturk ad server hosts ads, but then sends participants to experiment servers. 
* I think you mean h14, not 514.
* you mentioned before that you didn't want to upgrade to psiturk 3, but I'm guessing you're using the psiturk 3 docs. The heroku docs for the two versions are _not_ compatible. Regardless, I'm guessing you don't have a Procfile.

Please use the Google Groups for help requests-- github is for reporting bugs. Some people subscribe to one but not the other.

**Comment by deargle** [comment]
Also, if/when you post on the Google group, please provide enough details for someone else to be able to replicate your steps. Commands run, exact error messages, the like.
