### ISSUE TITLE
Setting enable_dashboard = true prevents the experiment from running

### ISSUE THREAD

**Issue by flxsosa** [NYUCCL/psiTurk#506]
When setting ```enable_dashboard = true``` in the ```config.txt``` on Psiturk v3.2.0, the experiment doesn't run locally or remotely on Heroku. Locally, after running ```debug```, the experiment page persistently loads and never returns anything. Remotely, after running ```debug```, Heroku returns an application error stating the worker timed out.

Commenting out ```enable_dashboard = true``` to ```;enable_dashboard = true``` fixes the problem.

**Comment by deargle** [comment]
Check your logs (`heroku logs`, server.log) to see what's being thrown.

**Comment by flxsosa** [comment]
Thanks for mentioning that. It turns out that I'm missing the ```secret_key``` variable as well. But the documentation doesn't mention this nor what value it should be set at. Do you know how this should be set?

**Comment by flxsosa** [comment]
I answered my own question -- you can set the ```secret_key``` to any value you find satisfactory. 

It would be good if the documentation could be updated to note that you need to set ```secret_key``` as well as ```login_pw``` and ```login_username``` in order for the dashboard to work. Currently it only says you need ```login_pw``` and ```login_username```.

**Comment by deargle** [comment]
True true. Want to PR?

**Comment by flxsosa** [comment]
Happy to do so. Just made a PR!
