### ISSUE TITLE
advanced_quals_path specification is being ignored

### ISSUE THREAD

**Issue by ttomita** [NYUCCL/psiTurk#510]
I am trying to create a hit with a qualification test in sandbox mode, in which workers must achieve a specific score on it in order to access the HIT. I am using `psiTurk 3.1.0`. In the worker sandbox listing for the HIT, the qualification test doesn't appear (it just let's me access the HIT).

I have created the qualification in the sandbox using boto, and I have confirmed that it is listed in my requester sandbox. In my local `config.txt`, I have specified `advanced_quals_path = ./advanced_quals.json`. My `advanced_quals.json` file looks like this:

```
[
    {
        "QualificationTypeId": "3N949H8PVSF4OL2KJJXSTLDXOP2EC2",
        "Comparator": "EqualTo",
        "IntegerValues": [2]
    }
]
```
It might be worth mentioning that when I specify `require_quals = 3N949H8PVSF4OL2KJJXSTLDXOP2EC2 ` in `config.txt`, the qualification test successfully appears when trying to access the HIT in the worker sandbox. However, I need to use an `EqualTo` comparator rather than an `Exists` comparator.

**Comment by deargle** [comment]
Support for advanced_quals_path landed in 3.2.0

**Comment by deargle** [comment]
https://github.com/NYUCCL/psiTurk/blob/master/CHANGELOG.md#320

**Comment by ttomita** [comment]
It works beautifully now. Thanks!
