### ISSUE TITLE
Can't Find HTML Templates

### ISSUE THREAD

**Issue by lchen64** [NYUCCL/psiTurk#536]
Hi,

I'm getting this error in my logs :

RuntimeError: Missing one of the following templates: thanks-mturksubmit.html, closepopup.html.
Copy these over from a freshly-created psiturk example experiment.

But it seems that my experiment folder (HumanRWT) is nested inside the psiturk folder from which I am running the shell, and the two templates in the error message are in the static folder of HumanRWT as they should be, so jinja should be able to find them... Any idea what could be wrong? Thanks!

**Comment by deargle** [comment]
Going to close as not a psiturk bug -- please use the google group for use questions -- but you say `HumanRWT` is _nested_ inside the folder where your config.txt is, and that's not right. config.txt -- the directory from which you're running the `psiturk server on` command -- needs to be at the same level as your `/static` and `/templates` folders.

```
HumanRWT
|   config.txt
|---static
|---templates
|    |   thanks-mturksubmit.html
|    |   closepopup.html
|    |   ... and more .html files ...
```


`/HumanRWT$ psiturk server on`

**Comment by lchen64** [comment]
That is the exact configuration I have set up, sorry if I wasn't clear in my question.

**Comment by deargle** [comment]
As the Google group user also noted, if you're using heroku, then your git repo that you're pushing to heroku also needs to be at the same level as your config.txt. You don't mention whether your logs are from heroku, but I recall from previous posts that you're using that.

**Comment by lchen64** [comment]
Yeah I am. It is at the same level now but it still can't find templates
somehow
