### ISSUE TITLE
PsiTurk failing to build on Heroku

### ISSUE THREAD

**Issue by tfnribeiro** [NYUCCL/psiTurk#550]
Hello! 

I have been running an experiment on the Heroku server without any issues. However, I was trying to set up WhoopsYall to refund potential workers that run into issues.

I was following the same steps as before (documentation for running the experiment on Heroku) and now I seem to run into this issue when I deploy the application:

```
2022-09-15T10:27:20.854981+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
2022-09-15T10:27:20.854981+00:00 app[web.1]:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
2022-09-15T10:27:20.854981+00:00 app[web.1]: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```
I tried googling this error and it does seem related to the version of pyOpenSSL, with the recommendation to set it to 22.0.0, however, this causes another issue:

```
Collecting cmd2==0.6.7
remote:          Downloading cmd2-0.6.7.tar.gz (20 kB)
remote:          Preparing metadata (setup.py): started
remote:          Preparing metadata (setup.py): finished with status 'error'
remote:          error: subprocess-exited-with-error
remote:         
remote:          × python setup.py egg_info did not run successfully.
remote:          │ exit code: 1
remote:          ╰─> [1 lines of output]
remote:              error in cmd2 setup command: use_2to3 is invalid.
remote:              [end of output]
```

At first, I suspected something with the configuration of WhoopsYall, but I was able to replicate this using the example experiment created with psiturk-setup-example. 

Any help would be appreciated!

**Comment by jacob-lee** [comment]
Pyopenssl needs to be upgraded to version 22

**Comment by tfnribeiro** [comment]
I have tried that, but when I set 'pyOpenSSL==22.0.0' in the requirements file, deploying it to Heroku fails due to cmd2.

**Comment by tfnribeiro** [comment]
using pip freeze onto the Heroku working instance has allowed me to get it up and running again.

So I guess the issue is some of the packages collected that conflict with one another. If you need the requirements.txt file I can attach it.

**Comment by jacob-lee** [comment]
So I encountered the issue yesterday, and fixed as I described. However I
didn't run the test suite and I don't use heroku. Pasting in your
requirements.txt that resolved it may be useful.

**Comment by tfnribeiro** [comment]
[requirements_heroku.txt](https://github.com/NYUCCL/psiTurk/files/9575271/requirements_heroku.txt)

**Comment by tfnribeiro** [comment]
[requirements_heroku.txt](https://github.com/NYUCCL/psiTurk/files/9575287/requirements_heroku.txt)

Here you go! 

For the WhoopsYall application, I added the depedency needed (shortuuid) and that worked OK.

**Comment by Reeche** [comment]
I had similar problems and adding cryptography==36.0.2 in my requirements.txt solved the problem. 

AFAIK, there was an [update](https://github.com/pyca/pyopenssl/issues/1143) in the  cryptography package, which removes the flag X509_V_FLAG_CB_ISSUER_CHECK. However, this flag is needed for pyOpenSSL v19
One solution suggests to [upgrade pyOpenSSL to v22](https://askubuntu.com/questions/1428181/module-lib-has-no-attribute-x509-v-flag-cb-issuer-check). But pyOpenSSL v22 is not compatible with psiTurk, which requires pyOpenSSL v19. Adding cryptography==36.0.2 in my requirements.txt solved the problem. 

I hope that this helps!
