### ISSUE TITLE
Psiturk 2.3.12 Not Working.

### ISSUE THREAD

**Issue by RhtK07** [NYUCCL/psiTurk#564]
Hi,

I was using PsiTurk (version 2.3.12) to host my experiment successfully in the past year(2023). However, recently when I tried to host the experiment again(especially this year), I encountered the same(mentioned below) error repeatedly. I have tried various solutions suggested across different discussion groups, but none of them have worked. Posting here is my last resort in seeking a resolution.
 
Error Is.
Error during hit creation.
Response(Operation: create_hit | Status: error | Exception: HTTPSConnectionPool(host='api.psiturk.org', port=443): Max retries exceeded with url: /api/ad (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd83032d1f0>: Failed to establish a new connection: [Errno 110] Connection timed out')))
 
I would appreciate any help or suggestions to resolve this issue.

Best regards,
Rohit K.

**Comment by subtrex** [comment]
I am experiencing a similar issue with hit creation using psiturk. The hit creation was working well until last week, and now it throws this error.

Response(Operation: create_hit | Status: error | Exception: An error occurred (RequestError) when calling the CreateHITType operation: This user is not authorized to perform the requested operation. (1719952633673 s))

I haven't made any changes to the psiturk config, but I'm suddenly experiencing an authentication issue. Would appreciate any help on it.

**Comment by gureckis** [comment]
sorry 2.x is not supported anymore.  for about 2 years now the psiturk.org website has a message saying all psiturk-org services were being sunsetted.  see the [migration guide](https://psiturk.readthedocs.io/en/latest/migrating.html)
