### ISSUE TITLE
Improve server performance

### ISSUE THREAD

**Issue by jbmartin** [NYUCCL/psiTurk#73]
For experiments that transmit a lot of data, **psiTurk** often becomes slow or unresponsive. This is most likely because of [Gunicorns synchronous request model](http://docs.gunicorn.org/en/latest/design.html?highlight=sync%20workers), which is designed to only serve one request per worker. On servers with limited worker capacity (limited CPUs), multiple participants with slow internet connections can grind the server to a hault.  

Gunicorn can be easily extended to use async workers via the Greenlets, Tornado, Eventlet, or Gevent libraries. Using Eventlet, the exp-server-async branch 39e1d1771b9f4f709e082e39c31448753440dfde does just that. Alternatively, we could try putting Gunicorn behind nginx using a [reverse proxy](http://www.onurguzel.com/how-to-run-flask-applications-with-nginx-using-gunicorn/) (probabiliy difficult to automate), or replace Gunicorn with [Waitress](https://github.com/Pylons/waitress)(not as mature as Gunicorn).

**Comment by twiecki** [comment]
Any reason why this was closed? Seems like https://github.com/NYUCCL/psiTurk/commit/39e1d1771b9f4f709e082e39c31448753440dfde is a simple change that improves performance but which was never merged.
