### ISSUE TITLE
Consolidate status codes

### ISSUE THREAD

**Issue by annacoenen** [NYUCCL/psiTurk#92]
There are some older categories in the list of status codes (credited, as well as the difference between completed and submitted), which have lost meaning in the current version of psiturk, so we may want to consolidate this list at some point.

**Comment by RoyalTS** [comment]
Can I ask what status codes are still in active use and need to be set to get psiturk to do certain things? I'm trying to fit an existing experiment written as a Flask app into psiturk (see https://groups.google.com/forum/#!topic/psiturk/c72JbURRAWM) and am having a hard time figuring out what all of these status codes do and how to set them.

Are the /complete, /worker_complete and /worker_submitted routes even called by psyturk.js? Or do you just kick people back to the ad-server when the task has run its course?

**Comment by deargle** [comment]
See experiment.py for status code interpretation, and no.
