### ISSUE TITLE
Add lab mode

### ISSUE THREAD

**Issue by jbmartin** [NYUCCL/psiTurk#95]
Several people have expressed interest in a lab mode. This can be done with the current version, but it's a little unpolished and non-obvious.

**Comment by twiecki** [comment]
Any progress on this? Is it possible at all?

**Comment by deargle** [comment]
Sure, just generate and distrubute your own entry urls and use "mode=lab"
in the url instead. Skip /ad, go straight to /consent or wherever.

**Comment by twiecki** [comment]
Is there a difference to using `model=debug` which allows me to just use whatever IDs I want if I understand correctly?

**Comment by deargle** [comment]
You can use whatever ids you want for anything that's not "live" or
"sandbox". Model=debug in conjunction with prefixing other url parameters
with the string "debug" disables the "if you quit now, you'll be marked as
a quitter" functionality. Besides that, there would be no difference
between "mode=debug" and "live". Lool through experiment.py to see how it
all works, including the /complete route in there.

**Comment by deargle** [comment]
Sorry, "Besides that, there would be no difference between "mode=debug" and
**"lab"**"

**Comment by twiecki** [comment]
I couldn't find a note of "lab" in experiment.py?

**Comment by deargle** [comment]
Look at how "mode" is used in there. E.g., in /complete, if not "live" or
"sandbox" , then...

**Comment by twiecki** [comment]
I see, so it doesn't have to be `lab` but just not live, sandbox, or debug.

**Comment by deargle** [comment]
Right.
